OpenCPN/plugins

- .gitignore
- DEVELOPER-INFO.md
- Makefile
- README.md
- ocpn-plugins.xml
- tools/ocpn-metadata
Here we have
- An updated README, hopefully more sane at a quick glance (#2).
- The generated ocpn-plugins.xml is made part of the repo. I don't really like it,
but it was the solution I could make to work.
- Overall version and date is added to ocpn-metadata.xml (#4)
> Fixes for #2 and #4

- check-metadata-urls
Add new tool which checks that all tarball-url and info-url elements
are accessible. A python 3 script without external dependencies,
see script header for more.
> Add check-metadata-url url checking tool.

- ocpn-plugins.xml
> updated ocpn-plugins.xml with testplugin_pi metadata

- metadata/weather_routing-plugin-darwin-10.13.6.xml
- metadata/weather_routing-plugin-debian-10.xml
- metadata/weather_routing-plugin-fedora-29.xml
- metadata/weather_routing-plugin-flatpak-18.08.xml
- metadata/weather_routing-plugin-mingw-10.xml
- metadata/weather_routing-plugin-msvc-10.0.14393.xml
- metadata/weather_routing-plugin-ubuntu-16.04.xml
- metadata/weather_routing-plugin-ubuntu-18.04.xml
- ocpn-plugins.xml
Details for the repair ----however I need to get this automated.
[Plugin-wxrouting-repair-tarball-url.txt](https://github.com/OpenCPN/plugins/files/4233713/Plugin-wxrouting-repair-tarball-url.txt)
> repair incorrect tarball-url xml fields

- metadata/radar-plugin-darwin-10.13.6.xml
- metadata/radar-plugin-debian-10.xml
- metadata/radar-plugin-fedora-29.xml
- metadata/radar-plugin-flatpak-18.08.xml
- metadata/radar-plugin-mingw-10.xml
- metadata/radar-plugin-msvc-10.0.14393.xml
- metadata/radar-plugin-raspbian-10.xml
- metadata/radar-plugin-ubuntu-16.04.xml
- metadata/radar-plugin-ubuntu-18.04.xml
- metadata/radar-plugin-ubuntu-20.04.xml
- ocpn-plugins.xml
This should fix the issues with the Windows versions.
> Radar plugin update to 5.1.3.0.8503cd4

- metadata/ocpn_draw_pi-1.6.70.0_darwin-10.13.6-macos.xml
- metadata/ocpn_draw_pi-1.6.70.0_debian-10-buster.xml
- metadata/ocpn_draw_pi-1.6.70.0_fedora-29-fedora.xml
- metadata/ocpn_draw_pi-1.6.70.0_flatpak-18.08-flatpak.xml
- metadata/ocpn_draw_pi-1.6.70.0_mingw-10-mingw.xml
- metadata/ocpn_draw_pi-1.6.70.0_msvc-10.0.14393-MSVC.xml
- metadata/ocpn_draw_pi-1.6.70.0_raspbian-10-buster-armhf.xml
- metadata/ocpn_draw_pi-1.6.70.0_raspbian-9.4-stretch-armhf-1.xml
- metadata/ocpn_draw_pi-1.6.70.0_ubuntu-14.04-trusty.xml
- metadata/ocpn_draw_pi-1.6.70.0_ubuntu-16.04-xenial.xml
- metadata/ocpn_draw_pi-1.6.70.0_ubuntu-18.04-bionic-gtk3.xml
- metadata/ocpn_draw_pi-1.6.70.0_ubuntu-18.04-bionic.xml
- metadata/ocpn_draw_pi-1.6.70.0_ubuntu-20.04-focal.xml
- ocpn-plugins.xml
- tools/ocpn-metadata
Updated tools/ocpn-metadata to work
> Updated with OD 1.6.70

- metadata/NmeaConverter-plugin-debian-10.xml
- metadata/NmeaConverter-plugin-fedora-29.xml
- metadata/NmeaConverter-plugin-mingw-10.xml
- metadata/NmeaConverter-plugin-msvc-10.0.14393.xml
- metadata/NmeaConverter-plugin-raspbian-9.4.xml
- metadata/NmeaConverter-plugin-ubuntu-16.04.xml
- metadata/NmeaConverter-plugin-ubuntu-18.04.xml
- metadata/NmeaConverter-plugin-ubuntu-20.04.xml
- ocpn-plugins.xml
Hope I did everything right;-)
Dont have the macOS builds running yet.
> add nmeaconverter, win & linux

- metadata/VDR-plugin-darwin-10.13.6.xml
- metadata/VDR-plugin-debian-x86_64-10.xml
- metadata/VDR-plugin-fedora-x86_64-29.xml
- metadata/VDR-plugin-flatpak-18.08.xml
- metadata/VDR-plugin-mingw-10.xml
- metadata/VDR-plugin-msvc-10.0.14393.xml
- metadata/VDR-plugin-raspbian-armhf-10.xml
- metadata/VDR-plugin-raspbian-armhf-9.4.xml
- metadata/VDR-plugin-ubuntu-arm64-18.04.xml
- metadata/VDR-plugin-ubuntu-gtk3-x86_64-18.04.xml
- metadata/VDR-plugin-ubuntu-gtk3-x86_64-20.04.xml
- metadata/VDR-plugin-ubuntu-x86_64-14.04.xml
- metadata/VDR-plugin-ubuntu-x86_64-16.04.xml
- metadata/VDR-plugin-ubuntu-x86_64-18.04.xml
- ocpn-plugins.xml
checked all urls.  Found that testplugin has 7 urls that fail. These errors were there when I started. I have not fixed them. vdr_pi v1.2.3 all checks out.
> vdr_pi v1.2.3

- metadata/sar_pi-2.6.17.0-darwin-x86_64-10.13.6-macos.xml
- metadata/sar_pi-2.6.17.0-debian-x86_64-10-buster.xml
- metadata/sar_pi-2.6.17.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/sar_pi-2.6.17.0-mingw-x86_64-10-mingw.xml
- metadata/sar_pi-2.6.17.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/sar_pi-2.6.17.0-raspbian-armhf-10-buster-armhf.xml
- metadata/sar_pi-2.6.17.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/sar_pi-2.6.17.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/sar_pi-2.6.17.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/sar_pi-2.6.17.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/sar_pi-2.6.17.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/sar_pi-2.6.17.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/sar_pi-2.6.17.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Signed-off-by: Rasbats <miker@members.swis.net>
> sar_pi 2.6.17.0

- metadata/sar_pi-2.6.19.0-darwin-x86_64-10.13.6-macos.xml
- metadata/sar_pi-2.6.19.0-debian-x86_64-10-buster.xml
- metadata/sar_pi-2.6.19.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/sar_pi-2.6.19.0-mingw-x86_64-10-mingw.xml
- metadata/sar_pi-2.6.19.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/sar_pi-2.6.19.0-raspbian-armhf-10-buster-armhf.xml
- metadata/sar_pi-2.6.19.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/sar_pi-2.6.19.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/sar_pi-2.6.19.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/sar_pi-2.6.19.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/sar_pi-2.6.19.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/sar_pi-2.6.19.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/sar_pi-2.6.19.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Version patch to cater for missing package.
> sar_pi 2.6.19.0

- metadata/otcurrent_pi-2.7.6.1-darwin-x86_64-10.13.6-macos.xml
- metadata/otcurrent_pi-2.7.6.1-debian-x86_64-10-buster.xml
- metadata/otcurrent_pi-2.7.6.1-mingw-x86_64-10-mingw.xml
- metadata/otcurrent_pi-2.7.6.1-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/otcurrent_pi-2.7.6.1-raspbian-armhf-10-buster-armhf.xml
- metadata/otcurrent_pi-2.7.6.1-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/otcurrent_pi-2.7.6.1-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/otcurrent_pi-2.7.6.1-ubuntu-x86_64-14.04-trusty.xml
- metadata/otcurrent_pi-2.7.6.1-ubuntu-x86_64-16.04-xenial.xml
- metadata/otcurrent_pi-2.7.6.1-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/otcurrent_pi-2.7.6.1-ubuntu-x86_64-18.04-bionic.xml
- metadata/otcurrent_pi-2.7.6.1-ubuntu-x86_64-20.04-focal-gtk3.xml
First managed version otcurrent_pi.
> otcurrent_pi v2.7.6.1

- metadata/otcurrent_pi-2.7.7.1-darwin-x86_64-10.13.6-macos.xml
- metadata/otcurrent_pi-2.7.7.1-debian-x86_64-10-buster.xml
- metadata/otcurrent_pi-2.7.7.1-flatpak-x86_64-18.08-flatpak.xml
- metadata/otcurrent_pi-2.7.7.1-mingw-x86_64-10-mingw.xml
- metadata/otcurrent_pi-2.7.7.1-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/otcurrent_pi-2.7.7.1-raspbian-armhf-10-buster-armhf.xml
- metadata/otcurrent_pi-2.7.7.1-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/otcurrent_pi-2.7.7.1-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/otcurrent_pi-2.7.7.1-ubuntu-x86_64-14.04-trusty.xml
- metadata/otcurrent_pi-2.7.7.1-ubuntu-x86_64-16.04-xenial.xml
- metadata/otcurrent_pi-2.7.7.1-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/otcurrent_pi-2.7.7.1-ubuntu-x86_64-18.04-bionic.xml
- metadata/otcurrent_pi-2.7.7.1-ubuntu-x86_64-20.04-focal-gtk3.xml
Ran into upper/lower case problems. This should fix it.
> otcurrent-v2.7.7.1

- metadata/weather_routing_pi-1.13.11.0-darwin-x86_64-10.13.6-macos.xml
- metadata/weather_routing_pi-1.13.11.0-debian-x86_64-10-buster.xml
- metadata/weather_routing_pi-1.13.11.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/weather_routing_pi-1.13.11.0-mingw-x86_64-10-mingw.xml
- metadata/weather_routing_pi-1.13.11.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weather_routing_pi-1.13.11.0-raspbian-armhf-10-buster-armhf.xml
- metadata/weather_routing_pi-1.13.11.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/weather_routing_pi-1.13.11.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/weather_routing_pi-1.13.11.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/weather_routing_pi-1.13.11.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/weather_routing_pi-1.13.11.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/weather_routing_pi-1.13.11.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/weather_routing_pi-1.13.11.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Language files fixed
About Version number extended
Frontend2 updated to 1.0.124 Testplugin
> weather_routing_pi 1.13.11.0

- metadata/watchdog_pi-2.4.15.0-darwin-x86_64-10.13.6-macos.xml
- metadata/watchdog_pi-2.4.15.0-debian-x86_64-10-buster.xml
- metadata/watchdog_pi-2.4.15.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/watchdog_pi-2.4.15.0-mingw-x86_64-10-mingw.xml
- metadata/watchdog_pi-2.4.15.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/watchdog_pi-2.4.15.0-raspbian-armhf-10-buster-armhf.xml
- metadata/watchdog_pi-2.4.15.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/watchdog_pi-2.4.15.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/watchdog_pi-2.4.15.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/watchdog_pi-2.4.15.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/watchdog_pi-2.4.15.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/watchdog_pi-2.4.15.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/watchdog_pi-2.4.15.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- metadata/weatherfax_pi-1.9.9.0-darwin-x86_64-10.13.6-macos.xml
- metadata/weatherfax_pi-1.9.9.0-debian-x86_64-10-buster.xml
- metadata/weatherfax_pi-1.9.9.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/weatherfax_pi-1.9.9.0-mingw-x86_64-10-mingw.xml
- metadata/weatherfax_pi-1.9.9.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weatherfax_pi-1.9.9.0-raspbian-armhf-10-buster-armhf.xml
- metadata/weatherfax_pi-1.9.9.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/weatherfax_pi-1.9.9.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/weatherfax_pi-1.9.9.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/weatherfax_pi-1.9.9.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/weatherfax_pi-1.9.9.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/weatherfax_pi-1.9.9.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/weatherfax_pi-1.9.9.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Updates to Frontend2 v1.0.124 and documentation.
Fix weatherfax schedules..xml path so it works.
Also should work better in various environments, but not flatpak
> Rg master  watchdog 2.4.15.0,  weatherfax 1.9.9.0

- metadata/sar_pi-2.6.20.0-darwin-x86_64-10.13.6-macos.xml
- metadata/sar_pi-2.6.20.0-debian-x86_64-10-buster.xml
- metadata/sar_pi-2.6.20.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/sar_pi-2.6.20.0-mingw-x86_64-10-mingw.xml
- metadata/sar_pi-2.6.20.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/sar_pi-2.6.20.0-raspbian-armhf-10-buster-armhf.xml
- metadata/sar_pi-2.6.20.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/sar_pi-2.6.20.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/sar_pi-2.6.20.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/sar_pi-2.6.20.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/sar_pi-2.6.20.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/sar_pi-2.6.20.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/sar_pi-2.6.20.0-ubuntu-x86_64-20.04-focal-gtk3.xml
> sar_pi-2.6.20.0

- metadata/engine_dashboard_pi-1.2.0.0-darwin-x86_64-10.13.6-macos.xml
- metadata/engine_dashboard_pi-1.2.0.0-debian-x86_64-10-buster.xml
- metadata/engine_dashboard_pi-1.2.0.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/engine_dashboard_pi-1.2.0.0-mingw-x86_64-10-mingw.xml
- metadata/engine_dashboard_pi-1.2.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/engine_dashboard_pi-1.2.0.0-raspbian-armhf-10-buster-armhf.xml
- metadata/engine_dashboard_pi-1.2.0.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/engine_dashboard_pi-1.2.0.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/engine_dashboard_pi-1.2.0.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/engine_dashboard_pi-1.2.0.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/engine_dashboard_pi-1.2.0.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/engine_dashboard_pi-1.2.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/engine_dashboard_pi-1.2.0.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Engine Dashboard metadata files to be added to Plugin Manager Catalog.
All files passed XML/XSD checks and all urls checked.
> Engine Dashboard v1.2

- metadata/climatology_pi-1.4.18.4-android-arm64-16-android-arm64.xml
- metadata/climatology_pi-1.4.18.4-darwin-x86_64-10.14.4-macos.xml
- metadata/climatology_pi-1.4.18.4-debian-x86_64-10-buster.xml
- metadata/climatology_pi-1.4.18.4-mingw-x86_64-10-mingw.xml
- metadata/climatology_pi-1.4.18.4-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/climatology_pi-1.4.18.4-raspbian-armhf-10-buster-armhf.xml
- metadata/climatology_pi-1.4.18.4-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/climatology_pi-1.4.18.4-ubuntu-x86_64-14.04-trusty.xml
- metadata/climatology_pi-1.4.18.4-ubuntu-x86_64-16.04-xenial.xml
- metadata/climatology_pi-1.4.18.4-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/climatology_pi-1.4.18.4-ubuntu-x86_64-18.04-bionic.xml
- metadata/climatology_pi-1.4.18.4-ubuntu-x86_64-20.04-focal-gtk3.xml
Still failing: Flatpak and android-armhf
> climatology v1.4.18.4 + fe2 v1.0.146.4 fix icons

- metadata/engine_dashboard_pi-1.3.0.0-darwin-x86_64-10.14.4-macos.xml
- metadata/engine_dashboard_pi-1.3.0.0-debian-x86_64-10-buster.xml
- metadata/engine_dashboard_pi-1.3.0.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/engine_dashboard_pi-1.3.0.0-mingw-x86_64-10-mingw.xml
- metadata/engine_dashboard_pi-1.3.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/engine_dashboard_pi-1.3.0.0-raspbian-armhf-10-buster-armhf.xml
- metadata/engine_dashboard_pi-1.3.0.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/engine_dashboard_pi-1.3.0.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/engine_dashboard_pi-1.3.0.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/engine_dashboard_pi-1.3.0.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/engine_dashboard_pi-1.3.0.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/engine_dashboard_pi-1.3.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/engine_dashboard_pi-1.3.0.0-ubuntu-x86_64-20.04-focal-gtk3.xml
All files pass xsd & metadata url checks.
> Engine Dashboard v1.3

- metadata/TideFinder-1.3-darwin-10.13.6.xml
- metadata/TideFinder-1.3-debian-10.xml
- metadata/TideFinder-1.3-flatpak-18.08.xml
- metadata/TideFinder-1.3-mingw-10.xml
- metadata/TideFinder-1.3-msvc-10.0.14393.xml
- metadata/TideFinder-1.3-raspbian-10.xml
- metadata/TideFinder-1.3-raspbian-9.13.xml
- metadata/TideFinder-1.3-ubuntu-16.04.xml
- metadata/TideFinder-1.3-ubuntu-18.04.xml
- metadata/TideFinder-1.3-ubuntu-gtk3-18.04.xml
- metadata/TideFinder-1.3-ubuntu-gtk3-20.04.xml
Updated for the alternative managed workflow revisions.
> v1.3 TideFinder Beta Version

- metadata/TideFinder-1.4-darwin-10.13.6.xml
- metadata/TideFinder-1.4-debian-10.xml
- metadata/TideFinder-1.4-flatpak-18.08.xml
- metadata/TideFinder-1.4-msvc-10.0.14393.xml
- metadata/TideFinder-1.4-ubuntu-18.04.xml
- metadata/TideFinder-1.4-ubuntu-gtk3-18.04.xml
- metadata/TideFinder-1.4-ubuntu-gtk3-20.04.xml
- metadata/UKTides-1.1-darwin-10.13.6.xml
- metadata/UKTides-1.1-debian-10.xml
- metadata/UKTides-1.1-flatpak-18.08.xml
- metadata/UKTides-1.1-msvc-10.0.14393.xml
- metadata/UKTides-1.1-raspbian-10.xml
- metadata/UKTides-1.1-raspbian-9.13.xml
- metadata/UKTides-1.1-ubuntu-16.04.xml
- metadata/UKTides-1.1-ubuntu-18.04.xml
- metadata/UKTides-1.1-ubuntu-gtk3-18.04.xml
- metadata/UKTides-1.1-ubuntu-gtk3-20.04.xml
- metadata/otidalplan-0.8-darwin-10.13.6.xml
- metadata/otidalplan-0.8-debian-10.xml
- metadata/otidalplan-0.8-flatpak-18.08.xml
- metadata/otidalplan-0.8-msvc-10.0.14393.xml
- metadata/otidalplan-0.8-raspbian-10.xml
- metadata/otidalplan-0.8-raspbian-9.13.xml
- metadata/otidalplan-0.8-ubuntu-16.04.xml
- metadata/otidalplan-0.8-ubuntu-18.04.xml
- metadata/otidalplan-0.8-ubuntu-gtk3-18.04.xml
- metadata/otidalplan-0.8-ubuntu-gtk3-20.04.xml
Update for TideFinder.
Re-submission UKTides.
New Beta - otidalplan
> Beta Versions UKTides, otidalplan, TideFinder

- metadata/watchdog_pi-2.4.23.7-darwin-x86_64-10.14.4-macos.xml
- metadata/watchdog_pi-2.4.23.7-debian-x86_64-10-buster.xml
- metadata/watchdog_pi-2.4.23.7-flatpak-x86_64-18.08-flatpak.xml
- metadata/watchdog_pi-2.4.23.7-mingw-x86_64-10-mingw.xml
- metadata/watchdog_pi-2.4.23.7-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/watchdog_pi-2.4.23.7-raspbian-armhf-10.xml
- metadata/watchdog_pi-2.4.23.7-raspbian-armhf-9.13.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-arm64-18.04.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-x86_64-14.04-trusty.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-x86_64-16.04-xenial.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-x86_64-18.04-bionic.xml
- metadata/watchdog_pi-2.4.23.7-ubuntu-x86_64-20.04-focal-gtk3.xml
This is a temorary update from the alpha repository. 
Hope to add the depth alarm from Sean's repository next.
> watchdog v2.3.23.7 + fix svg & toggled icon

- metadata/otidalplan-0.9-darwin-10.13.6.xml
- metadata/otidalplan-0.9-debian-10.xml
- metadata/otidalplan-0.9-flatpak-18.08.xml
- metadata/otidalplan-0.9-mingw-10.xml
- metadata/otidalplan-0.9-msvc-10.0.14393.xml
- metadata/otidalplan-0.9-raspbian-10.xml
- metadata/otidalplan-0.9-raspbian-9.13.xml
- metadata/otidalplan-0.9-ubuntu-16.04.xml
- metadata/otidalplan-0.9-ubuntu-18.04.xml
- metadata/otidalplan-0.9-ubuntu-gtk3-18.04.xml
- metadata/otidalplan-0.9-ubuntu-gtk3-20.04.xml
Updated to cope with P_Dub radius turns.
Thanks again.
> Update otidalplan_pi now v0.9.4-beta

- metadata/statusbar_pi-0.7.8.0-android-arm64-16-android-arm64.xml
- metadata/statusbar_pi-0.7.8.0-android-armhf-16-android-armhf.xml
- metadata/statusbar_pi-0.7.8.0-darwin-x86_64-10.14.4-macos.xml
- metadata/statusbar_pi-0.7.8.0-debian-x86_64-10-buster.xml
- metadata/statusbar_pi-0.7.8.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/statusbar_pi-0.7.8.0-mingw-x86_64-10-mingw.xml
- metadata/statusbar_pi-0.7.8.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/statusbar_pi-0.7.8.0-raspbian-armhf-10.xml
- metadata/statusbar_pi-0.7.8.0-raspbian-armhf-9.13.xml
- metadata/statusbar_pi-0.7.8.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/statusbar_pi-0.7.8.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/statusbar_pi-0.7.8.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/statusbar_pi-0.7.8.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/statusbar_pi-0.7.8.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Many thanks to Jon Gough for his android magic repairs.
> statusbar v0.7.8.0 including android

- metadata/UKTides-1.1-darwin-10.13.6.xml
- metadata/UKTides-1.1-debian-10.xml
- metadata/UKTides-1.1-flatpak-18.08.xml
- metadata/UKTides-1.1-msvc-10.0.14393.xml
- metadata/UKTides-1.1-raspbian-10.xml
- metadata/UKTides-1.1-raspbian-9.13.xml
- metadata/UKTides-1.1-ubuntu-16.04.xml
- metadata/UKTides-1.1-ubuntu-18.04.xml
- metadata/UKTides-1.1-ubuntu-gtk3-18.04.xml
- metadata/UKTides-1.1-ubuntu-gtk3-20.04.xml
Now version 1.1.4
Fixes problems with MacOS
> Updated UKTides_pi

- pre-commit
Fix all sorts of problems in pre-commit hook. 
Closes: #385 
See also: #383
> pre-commit hook: Bugfixes and clean-up (#385).

- pre-commit
> pre-commit: Check also renamed files (#402).

- metadata/Radar-5.2-darwin-10.13.6.xml
- metadata/Radar-5.2-debian-10.xml
- metadata/Radar-5.2-flatpak-18.08.xml
- metadata/Radar-5.2-flatpak-20.08.xml
- metadata/Radar-5.2-flatpak-A64-20.08.xml
- metadata/Radar-5.2-msvc-10.0.14393.xml
- metadata/Radar-5.2-raspbian-10.xml
- metadata/Radar-5.2-raspbian-9.13.xml
- metadata/Radar-5.2-ubuntu-16.04.xml
- metadata/Radar-5.2-ubuntu-18.04.xml
- metadata/Radar-5.2-ubuntu-gtk3-18.04.xml
- metadata/Radar-5.2-ubuntu-gtk3-20.04.xml
A small bugfix/functionality release.
This has the new names for the files now that @leamas has kindly fixed this PI's ci tree.
> Radar plugin v5.2.2

- metadata/ShipDriver-2.8-android-arm64-A64-16.xml
- metadata/ShipDriver-2.8-android-armhf-16.xml
- metadata/ShipDriver-2.8-darwin-10.13.6.xml
- metadata/ShipDriver-2.8-debian-10.xml
- metadata/ShipDriver-2.8-flatpak-18.08.xml
- metadata/ShipDriver-2.8-flatpak-20.08.xml
- metadata/ShipDriver-2.8-flatpak-A64-20.08.xml
- metadata/ShipDriver-2.8-msvc-10.0.14393.xml
- metadata/ShipDriver-2.8-raspbian-10.xml
- metadata/ShipDriver-2.8-raspbian-9.13.xml
- metadata/ShipDriver-2.8-ubuntu-16.04.xml
- metadata/ShipDriver-2.8-ubuntu-18.04.xml
- metadata/ShipDriver-2.8-ubuntu-gtk3-18.04.xml
- metadata/ShipDriver-2.8-ubuntu-gtk3-20.04.xml
Many changes made to the ShipDriver template build scripts. This beta is to test the workflow.
> v2.8.4.7-beta

- metadata/ShipDriver-v2.8.5.1-beta-android-arm64-A64-16.xml
- metadata/ShipDriver-v2.8.5.1-beta-android-armhf-16.xml
- metadata/ShipDriver-v2.8.5.1-beta-darwin-10.13.6.xml
- metadata/ShipDriver-v2.8.5.1-beta-debian-10.xml
- metadata/ShipDriver-v2.8.5.1-beta-flatpak-18.08.xml
- metadata/ShipDriver-v2.8.5.1-beta-flatpak-20.08.xml
- metadata/ShipDriver-v2.8.5.1-beta-flatpak-A64-20.08.xml
- metadata/ShipDriver-v2.8.5.1-beta-msvc-10.0.14393.xml
- metadata/ShipDriver-v2.8.5.1-beta-raspbian-10.xml
- metadata/ShipDriver-v2.8.5.1-beta-raspbian-9.13.xml
- metadata/ShipDriver-v2.8.5.1-beta-ubuntu-16.04.xml
- metadata/ShipDriver-v2.8.5.1-beta-ubuntu-18.04.xml
- metadata/ShipDriver-v2.8.5.1-beta-ubuntu-gtk3-18.04.xml
- metadata/ShipDriver-v2.8.5.1-beta-ubuntu-gtk3-20.04.xml
Sorry ... further changes and test for the workflow. Alec is now including tag names in the metadata file names.
> v2.8.5.1-beta

- metadata/weather_routing_pi-1.13.30.0-darwin-x86_64-11.4-macos.xml
- metadata/weather_routing_pi-1.13.30.0-debian-x86_64-10-buster.xml
- metadata/weather_routing_pi-1.13.30.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/weather_routing_pi-1.13.30.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/weather_routing_pi-1.13.30.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/weather_routing_pi-1.13.30.0-mingw-x86_64-10-mingw.xml
- metadata/weather_routing_pi-1.13.30.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weather_routing_pi-1.13.30.0-raspbian-armhf-10.xml
- metadata/weather_routing_pi-1.13.30.0-raspbian-armhf-9.13.xml
- metadata/weather_routing_pi-1.13.30.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/weather_routing_pi-1.13.30.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/weather_routing_pi-1.13.30.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/weather_routing_pi-1.13.30.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- Partial Fixes for android builds - not yet working  datactrl  and timectrl issue.
- Revert boat.xml and example polar files to be as described in the manual.
- Update to TP 1.0.174 frontend.
> weather_routing v1.13.30.0

- metadata/sar-2.8-darwin-10.13.6.xml
- metadata/sar-2.8-debian-10.xml
- metadata/sar-2.8-flatpak-18.08.xml
- metadata/sar-2.8-flatpak-A64-20.08.xml
- metadata/sar-2.8-mingw-10.xml
- metadata/sar-2.8-msvc-10.0.14393.xml
- metadata/sar-2.8-raspbian-10.xml
- metadata/sar-2.8-raspbian-9.13.xml
- metadata/sar-2.8-ubuntu-16.04.xml
- metadata/sar-2.8-ubuntu-18.04.xml
- metadata/sar-2.8-ubuntu-gtk3-18.04.xml
- metadata/sar-2.8-ubuntu-gtk3-20.04.xml
Remove sar-2.7
Incorporate changes to manual.
> Update to v2.8.2

- metadata/Calculator-v3.0.0-android-arm64-A64-16.xml
- metadata/Calculator-v3.0.0-android-armhf-16.xml
- metadata/Calculator-v3.0.0-darwin-wx315-10.13.6.xml
- metadata/Calculator-v3.0.0-debian-10.xml
- metadata/Calculator-v3.0.0-flatpak-18.08.xml
- metadata/Calculator-v3.0.0-flatpak-20.08.xml
- metadata/Calculator-v3.0.0-flatpak-A64-20.08.xml
- metadata/Calculator-v3.0.0-msvc-10.0.14393.xml
- metadata/Calculator-v3.0.0-ubuntu-16.04.xml
- metadata/Calculator-v3.0.0-ubuntu-18.04.xml
- metadata/Calculator-v3.0.0-ubuntu-gtk3-18.04.xml
- metadata/Calculator-v3.0.0-ubuntu-gtk3-20.04.xml
Move to managed version. Android versions included.
> Calculator_pi v3.0.0

- metadata/weather_routing_pi-1.13.34.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/weather_routing_pi-1.13.34.0-darwin-x86_64-11.4-macos.xml
- metadata/weather_routing_pi-1.13.34.0-debian-x86_64-10-buster.xml
- metadata/weather_routing_pi-1.13.34.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/weather_routing_pi-1.13.34.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/weather_routing_pi-1.13.34.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/weather_routing_pi-1.13.34.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weather_routing_pi-1.13.34.0-raspbian-armhf-10.xml
- metadata/weather_routing_pi-1.13.34.0-raspbian-armhf-9.13.xml
- metadata/weather_routing_pi-1.13.34.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/weather_routing_pi-1.13.34.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/weather_routing_pi-1.13.34.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/weather_routing_pi-1.13.34.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- ocpn-plugins.xml
I believe the problem plugin is Climatology when working with WR
There may be some broad PI problems with MacOS due to some specific thing.
> add WR 1.13.34.0 back

- metadata/dashboard_tactics_pi-1.6.11.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/dashboard_tactics_pi-1.6.11.0-darwin-x86_64-11.4-macos.xml
- metadata/dashboard_tactics_pi-1.6.11.0-debian-x86_64-10-buster.xml
- metadata/dashboard_tactics_pi-1.6.11.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/dashboard_tactics_pi-1.6.11.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/dashboard_tactics_pi-1.6.11.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/dashboard_tactics_pi-1.6.11.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/dashboard_tactics_pi-1.6.11.0-raspbian-armhf-10.xml
- metadata/dashboard_tactics_pi-1.6.11.0-raspbian-armhf-9.13.xml
- metadata/dashboard_tactics_pi-1.6.11.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/dashboard_tactics_pi-1.6.11.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/dashboard_tactics_pi-1.6.11.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/dashboard_tactics_pi-1.6.11.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- metadata/tactics_pi-1.0.26.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/tactics_pi-1.0.26.0-darwin-x86_64-11.4-macos.xml
- metadata/tactics_pi-1.0.26.0-debian-x86_64-10-buster.xml
- metadata/tactics_pi-1.0.26.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/tactics_pi-1.0.26.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/tactics_pi-1.0.26.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/tactics_pi-1.0.26.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/tactics_pi-1.0.26.0-raspbian-armhf-10.xml
- metadata/tactics_pi-1.0.26.0-raspbian-armhf-9.13.xml
- metadata/tactics_pi-1.0.26.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/tactics_pi-1.0.26.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/tactics_pi-1.0.26.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/tactics_pi-1.0.26.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- ocpn-plugins.xml
Dave, I hope tactics is ok too.
Thanks for all your help!
> dash-t 1.6.11 tactics 1.0.26  updated for Raspbian

- metadata/ais-vd-1.3-darwin-wx315-10.13.6.xml
- metadata/ais-vd-1.3-debian-10.xml
- metadata/ais-vd-1.3-flatpak-18.08.xml
- metadata/ais-vd-1.3-flatpak-20.08.xml
- metadata/ais-vd-1.3-flatpak-A64-20.08.xml
- metadata/ais-vd-1.3-msvc-10.0.14393.xml
- metadata/ais-vd-1.3-raspbian-11.xml
- metadata/ais-vd-1.3-ubuntu-16.04.xml
- metadata/ais-vd-1.3-ubuntu-18.04.xml
- metadata/ais-vd-1.3-ubuntu-gtk3-18.04.xml
- metadata/ais-vd-1.3-ubuntu-gtk3-20.04.xml
- metadata/ais-vd-1.4-darwin-wx315-10.13.6.xml
- metadata/ais-vd-1.4-debian-10.xml
- metadata/ais-vd-1.4-flatpak-18.08.xml
- metadata/ais-vd-1.4-flatpak-20.08.xml
- metadata/ais-vd-1.4-flatpak-A64-20.08.xml
- metadata/ais-vd-1.4-msvc-10.0.14393.xml
- metadata/ais-vd-1.4-raspbian-11.xml
- metadata/ais-vd-1.4-ubuntu-16.04.xml
- metadata/ais-vd-1.4-ubuntu-18.04.xml
- metadata/ais-vd-1.4-ubuntu-gtk3-18.04.xml
- metadata/ais-vd-1.4-ubuntu-gtk3-20.04.xml
- metadata/ais-vd-1.4.0-msvc-10.0.14393.xml
A few language update.
New icon logic by the help of Leamas
> ais-vd_pi version 1.4.0

- metadata/vfkaps-v3.1.0-darwin-wx315-10.13.6.xml
- metadata/vfkaps-v3.1.0-debian-10.xml
- metadata/vfkaps-v3.1.0-flatpak-18.08.xml
- metadata/vfkaps-v3.1.0-flatpak-20.08.xml
- metadata/vfkaps-v3.1.0-flatpak-A64-20.08.xml
- metadata/vfkaps-v3.1.0-msvc-10.0.14393.xml
- metadata/vfkaps-v3.1.0-raspbian-11.xml
- metadata/vfkaps-v3.1.0-ubuntu-16.04.xml
- metadata/vfkaps-v3.1.0-ubuntu-18.04.xml
- metadata/vfkaps-v3.1.0-ubuntu-gtk3-18.04.xml
- metadata/vfkaps-v3.1.0-ubuntu-gtk3-20.04.xml
v3.0.0 removed.
Sorry Dave ... needed a correction to allow preferences to be retained.
> VFKaps v3.1.0.

- metadata/sar-v3.0.0-android-arm64-A64-16.xml
- metadata/sar-v3.0.0-android-armhf-16.xml
- metadata/sar-v3.0.0-darwin-wx315-10.13.6.xml
- metadata/sar-v3.0.0-debian-10.xml
- metadata/sar-v3.0.0-flatpak-20.08.xml
- metadata/sar-v3.0.0-flatpak-A64-20.08.xml
- metadata/sar-v3.0.0-msvc-10.0.14393.xml
- metadata/sar-v3.0.0-raspbian-10.xml
- metadata/sar-v3.0.0-raspbian-11.xml
- metadata/sar-v3.0.0-raspbian-9.13.xml
- metadata/sar-v3.0.0-ubuntu-16.04.xml
- metadata/sar-v3.0.0-ubuntu-18.04.xml
- metadata/sar-v3.0.0-ubuntu-gtk3-18.04.xml
- metadata/sar-v3.0.0-ubuntu-gtk3-20.04.xml
Update sar_pi to v3.0.0 for O5.6
> sar v3.0.0

- metadata/otcurrent-v3.2.0-android-arm64-A64-16.xml
- metadata/otcurrent-v3.2.0-android-armhf-16.xml
- metadata/otcurrent-v3.2.0-darwin-wx315-10.13.6.xml
- metadata/otcurrent-v3.2.0-debian-10.xml
- metadata/otcurrent-v3.2.0-flatpak-18.08.xml
- metadata/otcurrent-v3.2.0-flatpak-20.08.xml
- metadata/otcurrent-v3.2.0-flatpak-A64-20.08.xml
- metadata/otcurrent-v3.2.0-msvc-10.0.14393.xml
- metadata/otcurrent-v3.2.0-raspbian-11.xml
- metadata/otcurrent-v3.2.0-ubuntu-16.04.xml
- metadata/otcurrent-v3.2.0-ubuntu-18.04.xml
- metadata/otcurrent-v3.2.0-ubuntu-gtk3-18.04.xml
- metadata/otcurrent-v3.2.0-ubuntu-gtk3-20.04.xml
Allow the dialog to expand instead of hard-coding sizes.
> otcurrent_pi Remove v3.1.0 Add v3.2.0

- metadata/UKTides-v1.1.0-android-arm64-A64-16.xml
- metadata/UKTides-v1.1.0-android-armhf-16.xml
- metadata/UKTides-v1.1.0-darwin-wx315-10.13.6.xml
- metadata/UKTides-v1.1.0-debian-10.xml
- metadata/UKTides-v1.1.0-flatpak-18.08.xml
- metadata/UKTides-v1.1.0-flatpak-20.08.xml
- metadata/UKTides-v1.1.0-flatpak-A64-20.08.xml
- metadata/UKTides-v1.1.0-msvc-10.0.14393.xml
- metadata/UKTides-v1.1.0-raspbian-11.xml
- metadata/UKTides-v1.1.0-ubuntu-16.04.xml
- metadata/UKTides-v1.1.0-ubuntu-18.04.xml
- metadata/UKTides-v1.1.0-ubuntu-gtk3-18.04.xml
- metadata/UKTides-v1.1.0-ubuntu-gtk3-20.04.xml
Addition to the master catalog. Now includes an Android version.
> UKTides v1.1.0 master catalog

- metadata/vfkaps-v3.2.0-darwin-wx315-10.13.6.xml
- metadata/vfkaps-v3.2.0-debian-10.xml
- metadata/vfkaps-v3.2.0-flatpak-18.08.xml
- metadata/vfkaps-v3.2.0-flatpak-20.08.xml
- metadata/vfkaps-v3.2.0-flatpak-A64-20.08.xml
- metadata/vfkaps-v3.2.0-msvc-10.0.14393.xml
- metadata/vfkaps-v3.2.0-raspbian-10.xml
- metadata/vfkaps-v3.2.0-raspbian-11.xml
- metadata/vfkaps-v3.2.0-raspbian-9.13.xml
- metadata/vfkaps-v3.2.0-ubuntu-16.04.xml
- metadata/vfkaps-v3.2.0-ubuntu-18.04.xml
- metadata/vfkaps-v3.2.0-ubuntu-gtk3-18.04.xml
- metadata/vfkaps-v3.2.0-ubuntu-gtk3-20.04.xml
> VFKaps v3.2.0

- metadata/javascript-v1.0.0b-darwin-wx315-10.13.6.xml
- metadata/javascript-v1.0.0b-debian-10.xml
- metadata/javascript-v1.0.0b-flatpak-20.08.xml
- metadata/javascript-v1.0.0b-flatpak-A64-20.08.xml
- metadata/javascript-v1.0.0b-msvc-10.0.14393.xml
- metadata/javascript-v1.0.0b-raspbian-11.xml
- metadata/javascript-v1.0.0b-ubuntu-18.04.xml
- metadata/javascript-v1.0.0b-ubuntu-gtk3-18.04.xml
- metadata/javascript-v1.0.0b-ubuntu-gtk3-20.04.xml
Before, my Cloudsmith prod repo was not set up as Open Source
> javascript_pi v1.0.0 try 2

- metadata/climatology_pi-1.4.40.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/climatology_pi-1.4.40.0-darwin-x86_64-11.4-macos.xml
- metadata/climatology_pi-1.4.40.0-debian-armhf-10.xml
- metadata/climatology_pi-1.4.40.0-debian-armhf-11.xml
- metadata/climatology_pi-1.4.40.0-debian-x86_64-10-buster.xml
- metadata/climatology_pi-1.4.40.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/climatology_pi-1.4.40.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/climatology_pi-1.4.40.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/climatology_pi-1.4.40.0-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/climatology_pi-1.4.40.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/climatology_pi-1.4.40.0-raspbian-armhf-9.13.xml
- metadata/climatology_pi-1.4.40.0-ubuntu-armhf-18.04.xml
- metadata/climatology_pi-1.4.40.0-ubuntu-armhf-20.04.xml
- metadata/climatology_pi-1.4.40.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/climatology_pi-1.4.40.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/climatology_pi-1.4.40.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- ocpn-plugins.xml
When "Currents" are checked, the Jan 29 --> change to Feb freeze problem (O fails)  still exists.
There are a few other issues too. See  https://github.com/seandepagnier/climatology_pi/issues/82
This is basically a trial run, with hopes that these issues will get resolved in the next version.
> Climatology 1.4.40.0  + TP1.0.193 + some fixes

- metadata/polar_pi-1.1.26.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/polar_pi-1.1.26.0-darwin-x86_64-11.4-macos.xml
- metadata/polar_pi-1.1.26.0-debian-armhf-10.xml
- metadata/polar_pi-1.1.26.0-debian-armhf-11.xml
- metadata/polar_pi-1.1.26.0-debian-x86_64-10-buster.xml
- metadata/polar_pi-1.1.26.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/polar_pi-1.1.26.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/polar_pi-1.1.26.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/polar_pi-1.1.26.0-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/polar_pi-1.1.26.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/polar_pi-1.1.26.0-raspbian-armhf-9.13.xml
- metadata/polar_pi-1.1.26.0-ubuntu-armhf-18.04.xml
- metadata/polar_pi-1.1.26.0-ubuntu-armhf-20.04.xml
- metadata/polar_pi-1.1.26.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/polar_pi-1.1.26.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/polar_pi-1.1.26.0-ubuntu-x86_64-20.04-focal-gtk3.xml
nmea moved back to src/nmea0183.  nmea is not standard.  Used standard libs/wxJSon
> polar 1.1.26

- metadata/Logbook-v1.4.29-darwin-wx315-10.13.6.xml
- metadata/Logbook-v1.4.29-debian-10.xml
- metadata/Logbook-v1.4.29-debian-11.xml
- metadata/Logbook-v1.4.29-debian-A32-10.xml
- metadata/Logbook-v1.4.29-debian-A32-11.xml
- metadata/Logbook-v1.4.29-flatpak-20.08.xml
- metadata/Logbook-v1.4.29-flatpak-A64-20.08.xml
- metadata/Logbook-v1.4.29-msvc-10.0.14393.xml
- metadata/Logbook-v1.4.29-ubuntu-18.04.xml
- metadata/Logbook-v1.4.29-ubuntu-A32-18.04.xml
- metadata/Logbook-v1.4.29-ubuntu-gtk3-18.04.xml
- metadata/Logbook-v1.4.29-ubuntu-gtk3-20.04.xml
- metadata/Logbook-v1.4.29-ubuntu-gtk3-A32-20.04.xml
Sorry this whole business has gotten me out of sync.  Alec was very patient, but something was not working and I think the open "Auto" push to opencpn/plugins was sending many unneccessary failures to me.  I closed that too.
For logbook I just deleted this metadata   
Logbook-v1.4.29-ubuntu-wx315-20.04
It is NOT accepted.
I am also DONE with this for the next 3 months.
Many thanks to Alec for all his help and support. Unfortunately this second step is not working for me.
Also I would like to thank Alec for his extraordinary persistence and talent in getting the PIM system working. We would never be able to support so many environments without it. That is a simple fact!
> logbookkonni 1.4.28  (this is wrong too should be 1.4.29!)

- metadata/watchdog_pi-2.4.42.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/watchdog_pi-2.4.42.0-darwin-x86_64-11.4-macos.xml
- metadata/watchdog_pi-2.4.42.0-debian-armhf-10.xml
- metadata/watchdog_pi-2.4.42.0-debian-armhf-11.xml
- metadata/watchdog_pi-2.4.42.0-debian-x86_64-10-buster.xml
- metadata/watchdog_pi-2.4.42.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/watchdog_pi-2.4.42.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/watchdog_pi-2.4.42.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/watchdog_pi-2.4.42.0-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/watchdog_pi-2.4.42.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/watchdog_pi-2.4.42.0-raspbian-armhf-9.13.xml
- metadata/watchdog_pi-2.4.42.0-ubuntu-armhf-18.04.xml
- metadata/watchdog_pi-2.4.42.0-ubuntu-armhf-20.04.xml
- metadata/watchdog_pi-2.4.42.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/watchdog_pi-2.4.42.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/watchdog_pi-2.4.42.0-ubuntu-x86_64-20.04-focal-gtk3.xml
With many thanks to Werner Toonk for this new alarm.
> watchdog 2.4.42 with rudder alarm

- metadata/twocan_plugin_pi-2.1.0.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/twocan_plugin_pi-2.1.0.0-darwin-x86_64-11.4-macos.xml
- metadata/twocan_plugin_pi-2.1.0.0-debian-armhf-10-buster-armhf.xml
- metadata/twocan_plugin_pi-2.1.0.0-debian-armhf-11-bullseye-armhf.xml
- metadata/twocan_plugin_pi-2.1.0.0-debian-x86_64-10-buster.xml
- metadata/twocan_plugin_pi-2.1.0.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/twocan_plugin_pi-2.1.0.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/twocan_plugin_pi-2.1.0.0-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/twocan_plugin_pi-2.1.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/twocan_plugin_pi-2.1.0.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/twocan_plugin_pi-2.1.0.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/twocan_plugin_pi-2.1.0.0-ubuntu-armhf-20.04-focal-armhf.xml
- metadata/twocan_plugin_pi-2.1.0.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/twocan_plugin_pi-2.1.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/twocan_plugin_pi-2.1.0.0-ubuntu-x86_64-20.04-focal-gtk3.xml
- ocpn-plugins.xml
All files passed XSD and URL validation checks.
> TwoCan Version 2.1

- metadata/weatherfax_pi-1.9.34.2-darwin-wx315-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.34.2-darwin-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.34.2-debian-armhf-10-buster-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-debian-armhf-11-bullseye-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-debian-x86_64-10-buster.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-x86_64-18.08-flatpak.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-x86_64-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.34.2-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weatherfax_pi-1.9.34.2-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-x86_64-18.04-bionic.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
Reverts coordinateSets change.  This now fails to download all DWD > Europe
> weatherfax 1.9.34.2

- metadata/weatherfax_pi-1.9.34.2-darwin-wx315-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.34.2-darwin-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.34.2-debian-armhf-10-buster-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-debian-armhf-11-bullseye-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-debian-x86_64-10-buster.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-x86_64-18.08-flatpak.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-x86_64-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.34.2-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.34.2-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weatherfax_pi-1.9.34.2-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-x86_64-18.04-bionic.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/weatherfax_pi-1.9.34.2-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
Reverts coordinateSets change. This now fails to download all DWD > Europe
> 1.9.34.2 revert coord

- metadata/nvc-v3.0.0-msvc-10.0.14393.xml
Adding a managed version of the NV Charts plugin. Hoping to save Dave R. some work. If all is well with the catalog intend asking Kathi to reinstate the page for nvc_pi and the plugins manual will be updated.
> nvc_pi v3.0.0

- metadata/statusbar_pi-0.7.23.0-android-arm64-16-android-arm64.xml
- metadata/statusbar_pi-0.7.23.0-android-armhf-16-android-armhf.xml
- metadata/statusbar_pi-0.7.23.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/statusbar_pi-0.7.23.0-darwin-x86_64-11.4-macos.xml
- metadata/statusbar_pi-0.7.23.0-debian-arm64-11-bullseye-arm64.xml
- metadata/statusbar_pi-0.7.23.0-debian-armhf-10-buster-armhf.xml
- metadata/statusbar_pi-0.7.23.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/statusbar_pi-0.7.23.0-debian-armhf-11-bullseye-armhf.xml
- metadata/statusbar_pi-0.7.23.0-debian-x86_64-10-buster.xml
- metadata/statusbar_pi-0.7.23.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/statusbar_pi-0.7.23.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/statusbar_pi-0.7.23.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/statusbar_pi-0.7.23.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/statusbar_pi-0.7.23.0-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/statusbar_pi-0.7.23.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/statusbar_pi-0.7.23.0-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/statusbar_pi-0.7.23.0-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
- metadata/statusbar_pi-0.7.23.0-ubuntu-x86_64-22.04-jammy.xml
> statusbar 0.7.23.0 but not flatpak

- metadata/weatherfax_pi-1.9.44.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.44.0-darwin-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.44.0-debian-arm64-11-bullseye-arm64.xml
- metadata/weatherfax_pi-1.9.44.0-debian-armhf-10-buster-armhf.xml
- metadata/weatherfax_pi-1.9.44.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/weatherfax_pi-1.9.44.0-debian-armhf-11-bullseye-armhf.xml
- metadata/weatherfax_pi-1.9.44.0-debian-x86_64-10-buster.xml
- metadata/weatherfax_pi-1.9.44.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/weatherfax_pi-1.9.44.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.44.0-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.44.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weatherfax_pi-1.9.44.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/weatherfax_pi-1.9.44.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/weatherfax_pi-1.9.44.0-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/weatherfax_pi-1.9.44.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/weatherfax_pi-1.9.44.0-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/weatherfax_pi-1.9.44.0-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
- metadata/weatherfax_pi-1.9.44.0-ubuntu-x86_64-22.04-jammy.xml
> weatherfax 1.9.44 + TP 1.0.216 FE2

- download_xml_bash.sh
- ocpn-plugin.xsd
- validate_xml.sh
The schema was missing values for several already existing targets and the new wx 3.2 targets
I have also slightly relaxed the wildcards matching the filenames in the download and validation scripts.
> Update the XML schema and slightly modify the download script

- metadata/weatherfax_pi-1.9.51.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.51.0-darwin-x86_64-11.4-macos.xml
- metadata/weatherfax_pi-1.9.51.0-debian-arm64-11-bullseye-arm64.xml
- metadata/weatherfax_pi-1.9.51.0-debian-armhf-10-buster-armhf.xml
- metadata/weatherfax_pi-1.9.51.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/weatherfax_pi-1.9.51.0-debian-armhf-11-bullseye-armhf.xml
- metadata/weatherfax_pi-1.9.51.0-debian-x86_64-10-buster.xml
- metadata/weatherfax_pi-1.9.51.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/weatherfax_pi-1.9.51.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/weatherfax_pi-1.9.51.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/weatherfax_pi-1.9.51.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/weatherfax_pi-1.9.51.0-msvc-x86_64-wx32-10.0.17763-MSVC.xml
- metadata/weatherfax_pi-1.9.51.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/weatherfax_pi-1.9.51.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/weatherfax_pi-1.9.51.0-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/weatherfax_pi-1.9.51.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/weatherfax_pi-1.9.51.0-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/weatherfax_pi-1.9.51.0-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
- metadata/weatherfax_pi-1.9.51.0-ubuntu-x86_64-22.04-jammy.xml
Ok made it to the right Beta branch.
> weatherfax 1.9.51 for O5.7.1 plugins/beta

- metadata/vfkaps-4.0-darwin-wx32-10.xml
- metadata/vfkaps-4.0-debian-11.xml
- metadata/vfkaps-4.0-debian-12.xml
- metadata/vfkaps-4.0-debian-A32-11.xml
- metadata/vfkaps-4.0-debian-A32-12.xml
- metadata/vfkaps-4.0-debian-A64-11.xml
- metadata/vfkaps-4.0-debian-A64-12.xml
- metadata/vfkaps-4.0-debian-wx32-A64-11.xml
- metadata/vfkaps-4.0-debian-wx32.wx32-11.xml
- metadata/vfkaps-4.0-flatpak-22.08.xml
- metadata/vfkaps-4.0-flatpak-A64-22.08.xml
- metadata/vfkaps-4.0-msvc-wx32-10.xml
- metadata/vfkaps-v4.0.0-msvc-wx32-10.0.14393.xml
v4.0.0 for OpenCPN 5.7.1-beta/5.8
Thanks.
> vfkaps v4.0.0

- metadata/Calculator-4.0-debian-12.xml
- metadata/Calculator-4.0-debian-A32-12.xml
- metadata/Calculator-4.0-debian-A64-12.xml
- metadata/Calculator-v4.0.0-android-arm64-A64-16.xml
- metadata/Calculator-v4.0.0-android-armhf-A32-16.xml
- metadata/Calculator-v4.0.0-darwin-wx32-10.xml
- metadata/Calculator-v4.0.0-debian-11.xml
- metadata/Calculator-v4.0.0-debian-A32-11.xml
- metadata/Calculator-v4.0.0-debian-A64-11.xml
- metadata/Calculator-v4.0.0-debian-wx32-A64-11.xml
- metadata/Calculator-v4.0.0-debian-wx32.wx32-11.xml
- metadata/Calculator-v4.0.0-flatpak-22.08.xml
- metadata/Calculator-v4.0.0-flatpak-A64-22.08.xml
- metadata/Calculator-v4.0.0-msvc-wx32-10.xml
- metadata/sar-3.0-darwin-wx32-10.xml
- metadata/sar-4.0-debian-12.xml
- metadata/sar-4.0-debian-A32-12.xml
- metadata/sar-4.0-debian-A64-12.xml
- metadata/sar-v4.0.0-android-arm64-A64-16.xml
- metadata/sar-v4.0.0-android-armhf-A32-16.xml
- metadata/sar-v4.0.0-darwin-wx32-10.xml
- metadata/sar-v4.0.0-debian-11.xml
- metadata/sar-v4.0.0-debian-A32-11.xml
- metadata/sar-v4.0.0-debian-A64-11.xml
- metadata/sar-v4.0.0-debian-wx32-A64-11.xml
- metadata/sar-v4.0.0-debian-wx32.wx32-11.xml
- metadata/sar-v4.0.0-flatpak-22.08.xml
- metadata/sar-v4.0.0-flatpak-A64-22.08.xml
- metadata/sar-v4.0.0-msvc-wx32-10.xml
> SAR_pi v4.0.0

- metadata/otidalplan-2.0-debian-12.xml
- metadata/otidalplan-2.0-debian-A32-12.xml
- metadata/otidalplan-2.0-debian-A64-12.xml
- metadata/otidalplan-v2.0.0-darwin-wx32-10.xml
- metadata/otidalplan-v2.0.0-debian-11.xml
- metadata/otidalplan-v2.0.0-debian-A32-11.xml
- metadata/otidalplan-v2.0.0-debian-A64-11.xml
- metadata/otidalplan-v2.0.0-debian-wx32-A64-11.xml
- metadata/otidalplan-v2.0.0-debian-wx32.wx32-11.xml
- metadata/otidalplan-v2.0.0-flatpak-22.08.xml
- metadata/otidalplan-v2.0.0-flatpak-A64-22.08.xml
- metadata/otidalplan-v2.0.0-msvc-wx32-10.xml
For OpenCPN 5.7.1-beta/5.8
Thanks.
> otidalplan v2.0.0

- metadata/pypilot_pi-0.36.0.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/pypilot_pi-0.36.0.0-darwin-x86_64-11.4-macos.xml
- metadata/pypilot_pi-0.36.0.0-debian-arm64-11-bullseye-arm64.xml
- metadata/pypilot_pi-0.36.0.0-debian-armhf-10-buster-armhf.xml
- metadata/pypilot_pi-0.36.0.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/pypilot_pi-0.36.0.0-debian-armhf-11-bullseye-armhf.xml
- metadata/pypilot_pi-0.36.0.0-debian-x86_64-10-buster.xml
- metadata/pypilot_pi-0.36.0.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/pypilot_pi-0.36.0.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/pypilot_pi-0.36.0.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/pypilot_pi-0.36.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/pypilot_pi-0.36.0.0-msvc-x86_64-wx32-10.0.17763-MSVC.xml
- metadata/pypilot_pi-0.36.0.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/pypilot_pi-0.36.0.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/pypilot_pi-0.36.0.0-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/pypilot_pi-0.36.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/pypilot_pi-0.36.0.0-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/pypilot_pi-0.36.0.0-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
- metadata/pypilot_pi-0.36.0.0-ubuntu-x86_64-22.04-jammy.xml
These changes polish the interface and improve nmea0183 handling. Need testing.
> pypilot 0.36.0 + sean's changes

- metadata/Radar-v5.5.0-beta-darwin-wx32-10.xml
- metadata/Radar-v5.5.0-beta-debian-11.xml
- metadata/Radar-v5.5.0-beta-debian-12.xml
- metadata/Radar-v5.5.0-beta-debian-A32-11.xml
- metadata/Radar-v5.5.0-beta-debian-A32-12.xml
- metadata/Radar-v5.5.0-beta-debian-A64-11.xml
- metadata/Radar-v5.5.0-beta-debian-A64-12.xml
- metadata/Radar-v5.5.0-beta-debian-wx32-A64-11.xml
- metadata/Radar-v5.5.0-beta-debian-wx32.wx32-11.xml
- metadata/Radar-v5.5.0-beta-flatpak-22.08.xml
- metadata/Radar-v5.5.0-beta-flatpak-A64-22.08.xml
- metadata/Radar-v5.5.0-beta-msvc-wx32-10.xml
Small updates to HALO, but more importantly added new targets compiled with wx3.2 to run against O 5.7 beta
> Radar v5.5.0-beta

- metadata/Launcher-v1.3.5-darwin-wx32-10.xml
Missing metadata file from delayed build
> Add Launcher metadata for macOS

- metadata/Projections-v0.3.0-darwin-wx32-10.xml
- metadata/Projections-v0.3.0-debian-11.xml
- metadata/Projections-v0.3.0-debian-12.xml
- metadata/Projections-v0.3.0-debian-A32-11.xml
- metadata/Projections-v0.3.0-debian-A32-12.xml
- metadata/Projections-v0.3.0-debian-A64-11.xml
- metadata/Projections-v0.3.0-debian-A64-12.xml
- metadata/Projections-v0.3.0-debian-wx32-11.xml
- metadata/Projections-v0.3.0-debian-wx32-A32-11.xml
- metadata/Projections-v0.3.0-debian-wx32-A64-11.xml
- metadata/Projections-v0.3.0-flatpak-22.08.xml
- metadata/Projections-v0.3.0-flatpak-A64-22.08.xml
- metadata/Projections-v0.3.0-msvc-wx32-10.0.20348.xml
Up to date build of Sean's projections plugin
> Add the projections plugin

- metadata/engine_dashboard_pi-1.5.0.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/engine_dashboard_pi-1.5.0.0-darwin-x86_64-11.4-macos.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-arm64-10-buster-arm64.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-arm64-11-bullseye-arm64.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-armhf-10-buster-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-armhf-11-bullseye-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-x86_64-10-buster.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-x86_64-11-bullseye.xml
- metadata/engine_dashboard_pi-1.5.0.0-debian-x86_64-12-bookworm.xml
- metadata/engine_dashboard_pi-1.5.0.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/engine_dashboard_pi-1.5.0.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/engine_dashboard_pi-1.5.0.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/engine_dashboard_pi-1.5.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/engine_dashboard_pi-1.5.0.0-msvc-x86_64-wx32-10.0.17763-MSVC.xml
- metadata/engine_dashboard_pi-1.5.0.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/engine_dashboard_pi-1.5.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/engine_dashboard_pi-1.5.0.0-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/engine_dashboard_pi-1.5.0.0-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
- metadata/engine_dashboard_pi-1.5.0.0-ubuntu-x86_64-22.04-jammy.xml
- ocpn-plugins.xml
Additional platforms from updtaed Front End build scripts.
XML validation and URL checks OK.
> Engine Dashboard v1.5.0.0

- metadata/MeteoVache-V1.0.0_beta-darwin-wx32-10.xml
- metadata/MeteoVache-V1.0.0_beta-debian-11.xml
- metadata/MeteoVache-V1.0.0_beta-debian-12.xml
- metadata/MeteoVache-V1.0.0_beta-debian-A32-11.xml
- metadata/MeteoVache-V1.0.0_beta-debian-A32-12.xml
- metadata/MeteoVache-V1.0.0_beta-debian-A64-11.xml
- metadata/MeteoVache-V1.0.0_beta-debian-A64-12.xml
- metadata/MeteoVache-V1.0.0_beta-debian-wx32-A64-11.xml
- metadata/MeteoVache-V1.0.0_beta-debian-wx32.wx32-11.xml
- metadata/MeteoVache-V1.0.0_beta-flatpak-22.08.xml
- metadata/MeteoVache-V1.0.0_beta-flatpak-A64-22.08.xml
- metadata/MeteoVache-V1.0.0_beta-msvc-wx32-10.xml
First attempt to insert *meteovache_pi* into official "beta" plug-in catalog
> meteovache_pi_1.0.0-beta

- metadata/MeteoVache-V1.0.3_beta-darwin-wx32-10.xml
- metadata/MeteoVache-V1.0.3_beta-debian-11.xml
- metadata/MeteoVache-V1.0.3_beta-debian-12.xml
- metadata/MeteoVache-V1.0.3_beta-debian-A32-11.xml
- metadata/MeteoVache-V1.0.3_beta-debian-A32-12.xml
- metadata/MeteoVache-V1.0.3_beta-debian-A64-11.xml
- metadata/MeteoVache-V1.0.3_beta-debian-A64-12.xml
- metadata/MeteoVache-V1.0.3_beta-debian-wx32-A64-11.xml
- metadata/MeteoVache-V1.0.3_beta-debian-wx32.wx32-11.xml
- metadata/MeteoVache-V1.0.3_beta-flatpak-22.08.xml
- metadata/MeteoVache-V1.0.3_beta-flatpak-A64-22.08.xml
- metadata/MeteoVache-V1.0.3_beta-msvc-wx32-10.xml
V1.0.3 fixing various issues of 1.0.1
> Meteovache 1.0.3-beta

- metadata/MeteoVache-1.0.5-beta-darwin-wx32-10.xml
- metadata/MeteoVache-1.0.5-beta-debian-12.xml
- metadata/MeteoVache-1.0.5-beta-debian-A32-11.xml
- metadata/MeteoVache-1.0.5-beta-debian-A32-12.xml
- metadata/MeteoVache-1.0.5-beta-debian-A64-12.xml
- metadata/MeteoVache-1.0.5-beta-debian-wx32-A64-11.xml
- metadata/MeteoVache-1.0.5-beta-debian-wx32.wx32-11.xml
- metadata/MeteoVache-1.0.5-beta-flatpak-22.08.xml
- metadata/MeteoVache-1.0.5-beta-flatpak-A64-22.08.xml
- metadata/MeteoVache-1.0.5-beta-msvc-wx32-10.xml
Add v1.0.5-beta and remove outdated versions
> Add meteovache_pi v1.0.5-beta

- metadata/windvane_pi-1.0.28.0-android-arm64-16-android-arm64.xml
- metadata/windvane_pi-1.0.28.0-android-armhf-16-android-armhf.xml
- metadata/windvane_pi-1.0.28.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/windvane_pi-1.0.28.0-darwin-x86_64-11.4-macos.xml
- metadata/windvane_pi-1.0.28.0-debian-arm64-10-buster-arm64.xml
- metadata/windvane_pi-1.0.28.0-debian-arm64-11-bullseye-arm64.xml
- metadata/windvane_pi-1.0.28.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/windvane_pi-1.0.28.0-debian-armhf-10-buster-armhf.xml
- metadata/windvane_pi-1.0.28.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/windvane_pi-1.0.28.0-debian-armhf-11-bullseye-armhf.xml
- metadata/windvane_pi-1.0.28.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/windvane_pi-1.0.28.0-debian-x86_64-10-buster.xml
- metadata/windvane_pi-1.0.28.0-debian-x86_64-11-bullseye.xml
- metadata/windvane_pi-1.0.28.0-debian-x86_64-12-bookworm.xml
- metadata/windvane_pi-1.0.28.0-debian-x86_64-22.04-jammy.xml
- metadata/windvane_pi-1.0.28.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/windvane_pi-1.0.28.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/windvane_pi-1.0.28.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/windvane_pi-1.0.28.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/windvane_pi-1.0.28.0-msvc-x86_64-wx32-10.0.17763-MSVC.xml
- metadata/windvane_pi-1.0.28.0-raspbian-armhf-9.13-stretch-armhf.xml
- metadata/windvane_pi-1.0.28.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/windvane_pi-1.0.28.0-ubuntu-armhf-20.04-gtk3-focal-armhf.xml
- metadata/windvane_pi-1.0.28.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/windvane_pi-1.0.28.0-ubuntu-x86_64-18.04-gtk3-bionic-gtk3.xml
- metadata/windvane_pi-1.0.28.0-ubuntu-x86_64-20.04-gtk3-focal-gtk3.xml
> Update to FE2 1.0.242.0

- metadata/ShipDriver-v3.3.0-beta3-android-arm64-A64-16.xml
- metadata/ShipDriver-v3.3.0-beta3-android-armhf-A32-16.xml
- metadata/ShipDriver-v3.3.0-beta3-darwin-wx32-10.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-11.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-12.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-A32-11.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-A32-12.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-A64-11.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-A64-12.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-wx32-11.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-wx32-A32-11.xml
- metadata/ShipDriver-v3.3.0-beta3-debian-wx32-A64-11.xml
- metadata/ShipDriver-v3.3.0-beta3-flatpak-22.08.xml
- metadata/ShipDriver-v3.3.0-beta3-flatpak-A64-22.08.xml
- metadata/ShipDriver-v3.3.0-beta3-msvc-wx32-10.xml
> ShipDriver v3.3.0 Beta

- metadata/watchdog_pi-2.4.61.0-android-arm64-16-android-arm64.xml
- metadata/watchdog_pi-2.4.61.0-android-armhf-16-android-armhf.xml
- metadata/watchdog_pi-2.4.61.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/watchdog_pi-2.4.61.0-darwin-x86_64-11.4-macos.xml
- metadata/watchdog_pi-2.4.61.0-debian-arm64-10-buster-arm64.xml
- metadata/watchdog_pi-2.4.61.0-debian-arm64-11-bullseye-arm64.xml
- metadata/watchdog_pi-2.4.61.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/watchdog_pi-2.4.61.0-debian-armhf-10-buster-armhf.xml
- metadata/watchdog_pi-2.4.61.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/watchdog_pi-2.4.61.0-debian-armhf-11-bullseye-armhf.xml
- metadata/watchdog_pi-2.4.61.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/watchdog_pi-2.4.61.0-debian-x86_64-10-buster.xml
- metadata/watchdog_pi-2.4.61.0-debian-x86_64-11-bullseye.xml
- metadata/watchdog_pi-2.4.61.0-debian-x86_64-12-bookworm.xml
- metadata/watchdog_pi-2.4.61.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/watchdog_pi-2.4.61.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/watchdog_pi-2.4.61.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/watchdog_pi-2.4.61.0-msvc-x86_64-wx32-10.0.20348-MSVC.xml
- metadata/watchdog_pi-2.4.61.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/watchdog_pi-2.4.61.0-ubuntu-x86_64-22.04-jammy.xml
> watchdog 2.4.61.0 fix android

- metadata/AutoTrackRaymarine_pi-1.18.4.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-darwin-x86_64-11.4-macos.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-arm64-10-buster-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-arm64-11-bullseye-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-armhf-10-buster-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-armhf-11-bullseye-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-x86_64-10-buster.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-x86_64-11-bullseye.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-debian-x86_64-12-bookworm.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-msvc-x86_64-wx32-10.0.20348-MSVC.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.4.0-ubuntu-x86_64-22.04-jammy.xml
See this thread please (also android does not build yet)
https://github.com/douwefokkema/AutoTrackRaymarine_pi/issues/22
> AutoTrackRaymarine 1.18.4.0 fails in Win

- metadata/AutoTrackRaymarine_pi-1.18.10.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-darwin-x86_64-11.4-macos.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-arm64-10-buster-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-arm64-11-bullseye-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-armhf-10-buster-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-armhf-11-bullseye-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-x86_64-10-buster.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-x86_64-11-bullseye.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-debian-x86_64-12-bookworm.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-msvc-x86_64-wx32-10.0.20348-MSVC.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/AutoTrackRaymarine_pi-1.18.10.0-ubuntu-x86_64-22.04-jammy.xml
@bdbcat Dave can you merge this for Douwe  and others to test on the Beta catalog? Thanks.
> AutoTrackRaymarine 1.18.10 18metadata

- metadata/deviation_pi-0.1.8.0-android-arm64-16-android-arm64.xml
- metadata/deviation_pi-0.1.8.0-android-armhf-16-android-armhf.xml
- metadata/deviation_pi-0.1.8.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/deviation_pi-0.1.8.0-darwin-x86_64-11.4-macos.xml
- metadata/deviation_pi-0.1.8.0-debian-arm64-10-buster-arm64.xml
- metadata/deviation_pi-0.1.8.0-debian-arm64-11-bullseye-arm64.xml
- metadata/deviation_pi-0.1.8.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/deviation_pi-0.1.8.0-debian-armhf-10-buster-armhf.xml
- metadata/deviation_pi-0.1.8.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/deviation_pi-0.1.8.0-debian-armhf-11-bullseye-armhf.xml
- metadata/deviation_pi-0.1.8.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/deviation_pi-0.1.8.0-debian-x86_64-10-buster.xml
- metadata/deviation_pi-0.1.8.0-debian-x86_64-11-bullseye.xml
- metadata/deviation_pi-0.1.8.0-debian-x86_64-12-bookworm.xml
- metadata/deviation_pi-0.1.8.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/deviation_pi-0.1.8.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/deviation_pi-0.1.8.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/deviation_pi-0.1.8.0-msvc-x86_64-wx32-10.0.20348-MSVC.xml
- metadata/deviation_pi-0.1.8.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/deviation_pi-0.1.8.0-ubuntu-x86_64-22.04-jammy.xml
> deviation 0.1.8.0

- metadata/engine_dashboard_pi-1.6.0.0-darwin-wx32-x86_64-11.4-macos.xml
- metadata/engine_dashboard_pi-1.6.0.0-debian-arm64-wx32-12-bookworm-arm64.xml
- metadata/engine_dashboard_pi-1.6.0.0-debian-armhf-wx32-12-bookworm-armhf.xml
- metadata/engine_dashboard_pi-1.6.0.0-debian-x86_64-12-bookworm.xml
- metadata/engine_dashboard_pi-1.6.0.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/engine_dashboard_pi-1.6.0.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/engine_dashboard_pi-1.6.0.0-msvc-x86_64-wx32-10.0.20348-MSVC.xml
- metadata/engine_dashboard_pi-1.6.0.0-ubuntu-x86_64-22.04-jammy.xml
- ocpn-plugins.xml
Hopefully fixed the merge conflicts.
> Engine Dashboard 1.6.0.0

- metadata/frcurrents-v1.0.2-beta1-android-arm64-A64-16.xml
- metadata/frcurrents-v1.0.2-beta1-android-armhf-A32-16.xml
- metadata/frcurrents-v1.0.2-beta1-darwin-wx32-10.xml
- metadata/frcurrents-v1.0.2-beta1-debian-11.xml
- metadata/frcurrents-v1.0.2-beta1-debian-arm64-A64-11.xml
- metadata/frcurrents-v1.0.2-beta1-debian-arm64-A64-12.xml
- metadata/frcurrents-v1.0.2-beta1-debian-armhf-A32-11.xml
- metadata/frcurrents-v1.0.2-beta1-debian-armhf-A32-12.xml
- metadata/frcurrents-v1.0.2-beta1-debian-wx32-arm64-A64-11.xml
- metadata/frcurrents-v1.0.2-beta1-debian-wx32-armhf-A32-11.xml
- metadata/frcurrents-v1.0.2-beta1-debian-wx32-x86_64.wx32-11.xml
- metadata/frcurrents-v1.0.2-beta1-debian-x86_64-12.xml
- metadata/frcurrents-v1.0.2-beta1-flatpak-22.08.xml
- metadata/frcurrents-v1.0.2-beta1-flatpak-A64-22.08.xml
- metadata/frcurrents-v1.0.2-beta1-msvc-wx32-10.xml
> frcurrents_pi v1.0.2-beta1

- metadata/engine_dashboard_pi-1.6.0.0-ubuntu-x86_64-22.04-jammy.xml
- ocpn-plugins.xml
Change tuple from <target>ubuntu-x86_64</target> to <target>ubuntu-wx32-x86_64</target>
> Fix Engine Dashboard v1.6 Jammy Target Tuple

- metadata/manual-v0.0.1-android-arm64-A64-16.xml
- metadata/manual-v0.0.1-android-armhf-A32-16.xml
- metadata/manual-v0.0.1-darwin-wx32-universal-10.xml
- metadata/manual-v0.0.1-debian-arm64-A64-11.xml
- metadata/manual-v0.0.1-debian-arm64-A64-12.xml
- metadata/manual-v0.0.1-debian-armhf-A32-11.xml
- metadata/manual-v0.0.1-debian-armhf-A32-12.xml
- metadata/manual-v0.0.1-debian-wx32-arm64-A64-11.xml
- metadata/manual-v0.0.1-debian-wx32-armhf-A32-11.xml
- metadata/manual-v0.0.1-debian-wx32-x86_64-11.xml
- metadata/manual-v0.0.1-debian-x86_64-11.xml
- metadata/manual-v0.0.1-debian-x86_64-12.xml
- metadata/manual-v0.0.1-flatpak-aarch64-A64-22.08.xml
- metadata/manual-v0.0.1-flatpak-x86_64-22.08.xml
- metadata/manual-v0.0.1-msvc-wx32-10.xml
- ocpn-plugins.xml
> New plugin manual_pi: First version

- metadata/VDR-v1.3.31-android-arm64-A64-16.xml
- metadata/VDR-v1.3.31-android-armhf-A32-16.xml
- metadata/VDR-v1.3.31-darwin-wx32-universal-10.xml
- metadata/VDR-v1.3.31-debian-arm64-A64-11.xml
- metadata/VDR-v1.3.31-debian-arm64-A64-12.xml
- metadata/VDR-v1.3.31-debian-armhf-A32-11.xml
- metadata/VDR-v1.3.31-debian-armhf-A32-12.xml
- metadata/VDR-v1.3.31-debian-wx32-arm64-A64-11.xml
- metadata/VDR-v1.3.31-debian-wx32-armhf-A32-11.xml
- metadata/VDR-v1.3.31-debian-wx32-x86_64-11.xml
- metadata/VDR-v1.3.31-debian-x86_64-11.xml
- metadata/VDR-v1.3.31-debian-x86_64-12.xml
- metadata/VDR-v1.3.31-flatpak-aarch64-A64-22.08.xml
- metadata/VDR-v1.3.31-flatpak-x86_64-22.08.xml
- metadata/VDR-v1.3.31-msvc-wx32-10.xml
with updated shipdriver frontend.
> vdr_pi v1.3.31

- metadata/weatherfax_pi-1.9.20.0-android-arm64-16-android-arm64.xml
- metadata/weatherfax_pi-1.9.20.0-android-armhf-16-android-armhf.xml
- metadata/weatherfax_pi-1.9.20.0-darwin-wx32-arm64-x86_64-12.6.1.xml
- metadata/weatherfax_pi-1.9.20.0-debian-arm64-11-bullseye-arm64.xml
- metadata/weatherfax_pi-1.9.20.0-debian-arm64-12-bookworm-arm64.xml
- metadata/weatherfax_pi-1.9.20.0-debian-arm64-12-bookworm.xml
- metadata/weatherfax_pi-1.9.20.0-debian-armhf-11-bullseye-armhf.xml
- metadata/weatherfax_pi-1.9.20.0-debian-armhf-12-bookworm-armhf.xml
- metadata/weatherfax_pi-1.9.20.0-debian-x86_64-11-bullseye.xml
- metadata/weatherfax_pi-1.9.20.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/weatherfax_pi-1.9.20.0-flatpak-aarch64-22.08-flatpak.xml
- metadata/weatherfax_pi-1.9.20.0-flatpak-aarch64-24.08-flatpak-arm64.xml
- metadata/weatherfax_pi-1.9.20.0-flatpak-aarch64-24.08-flatpak.xml
- metadata/weatherfax_pi-1.9.20.0-msvc-x86-10.0.20348-MSVC.xml
- metadata/weatherfax_pi-1.9.20.0-msvc-x86-wx32-10.0.20348-MSVC.xml
- metadata/weatherfax_pi-1.9.20.0-ubuntu-x86_64-22.04-jammy.xml
It says 16 files changed now, instead of 17!
> 1.9.20.0 + TP1.0.304.0 api117

- metadata/dashboard_tactics_pi-1.7.61.0-android-arm64-16-android-arm64.xml
- metadata/dashboard_tactics_pi-1.7.61.0-android-armhf-16-android-armhf.xml
- metadata/dashboard_tactics_pi-1.7.61.0-darwin-wx315-x86_64-12.3.1-macos.xml
- metadata/dashboard_tactics_pi-1.7.61.0-darwin-wx32-arm64-x86_64-11.4-macos.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-arm64-10-buster-arm64.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-arm64-11-bullseye-arm64.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-arm64-12-bookworm-arm64.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-armhf-10-buster-armhf.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-armhf-10-gtk3-buster-armhf.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-armhf-11-bullseye-armhf.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-armhf-12-bookworm-armhf.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-x86_64-10-buster.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-x86_64-11-bullseye.xml
- metadata/dashboard_tactics_pi-1.7.61.0-debian-x86_64-12-bookworm.xml
- metadata/dashboard_tactics_pi-1.7.61.0-flatpak-aarch64-22.08-flatpak-arm64.xml
- metadata/dashboard_tactics_pi-1.7.61.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/dashboard_tactics_pi-1.7.61.0-msvc-x86_64-10.0.20348-MSVC.xml
- metadata/dashboard_tactics_pi-1.7.61.0-msvc-x86_64-wx32-10.0.20348-MSVC.xml
- metadata/dashboard_tactics_pi-1.7.61.0-ubuntu-armhf-18.04-buster-armhf.xml
- metadata/dashboard_tactics_pi-1.7.61.0-ubuntu-x86_64-22.04-jammy.xml
> dashboard-tactics 1.7.61 + rm 1.7.65

- metadata/crowdsource_pi-0.1.183.0-android-arm64-16-android-arm64.xml
- metadata/crowdsource_pi-0.1.183.0-android-armhf-16-android-armhf.xml
- metadata/crowdsource_pi-0.1.183.0-darwin-wx315-x86_64-12.6.3-macos.xml
- metadata/crowdsource_pi-0.1.183.0-darwin-wx32-arm64-x86_64-12.6.3-macos.xml
- metadata/crowdsource_pi-0.1.183.0-debian-arm64-11-bullseye-arm64.xml
- metadata/crowdsource_pi-0.1.183.0-debian-arm64-12-bookworm-arm64.xml
- metadata/crowdsource_pi-0.1.183.0-debian-arm64-12-bookworm.xml
- metadata/crowdsource_pi-0.1.183.0-debian-armhf-11-bullseye-armhf.xml
- metadata/crowdsource_pi-0.1.183.0-debian-armhf-12-bookworm-armhf.xml
- metadata/crowdsource_pi-0.1.183.0-debian-x86_64-11-bullseye.xml
- metadata/crowdsource_pi-0.1.183.0-flatpak-aarch64-22.08-flatpak.xml
- metadata/crowdsource_pi-0.1.183.0-flatpak-aarch64-24.08-flatpak.xml
- metadata/crowdsource_pi-0.1.183.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/crowdsource_pi-0.1.183.0-flatpak-x86_64-24.08-flatpak.xml
- metadata/crowdsource_pi-0.1.183.0-msvc-x86-10.0.20348-MSVC.xml
- metadata/crowdsource_pi-0.1.183.0-msvc-x86-wx32-10.0.20348-MSVC.xml
- metadata/crowdsource_pi-0.1.183.0-ubuntu-x86_64-22.04-jammy.xml
See https://github.com/OpenCPN/plugins/issues/1199
> Added crowdsource v1.183

- metadata/celestial_navigation_pi-2.4.47.0-android-arm64-16-android-arm64.xml
- metadata/celestial_navigation_pi-2.4.47.0-android-armhf-16-android-armhf.xml
- metadata/celestial_navigation_pi-2.4.47.0-darwin-wx32-arm64-x86_64-14.1-macos.xml
- metadata/celestial_navigation_pi-2.4.47.0-debian-arm64-11-bullseye-arm64.xml
- metadata/celestial_navigation_pi-2.4.47.0-debian-arm64-12-bookworm-arm64.xml
- metadata/celestial_navigation_pi-2.4.47.0-debian-armhf-11-bullseye-armhf.xml
- metadata/celestial_navigation_pi-2.4.47.0-debian-armhf-12-bookworm-armhf.xml
- metadata/celestial_navigation_pi-2.4.47.0-debian-x86_64-11-bullseye.xml
- metadata/celestial_navigation_pi-2.4.47.0-debian-x86_64-12-bookworm.xml
- metadata/celestial_navigation_pi-2.4.47.0-flatpak-aarch64-22.08-flatpak.xml
- metadata/celestial_navigation_pi-2.4.47.0-flatpak-aarch64-24.08-flatpak.xml
- metadata/celestial_navigation_pi-2.4.47.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/celestial_navigation_pi-2.4.47.0-flatpak-x86_64-24.08-flatpak.xml
- metadata/celestial_navigation_pi-2.4.47.0-msvc-x86-10.0.20348-MSVC.xml
- metadata/celestial_navigation_pi-2.4.47.0-msvc-x86-wx32-10.0.20348-MSVC.xml
- metadata/celestial_navigation_pi-2.4.47.0-ubuntu-x86_64-22.04-jammy.xml
Big improvements for accuracy with lots of testing done.
Bob Bossert and Stelian
> cel-nav 2.4.47.0

- metadata/frcurrents-1.16.1-android-arm64-A64-16.xml
- metadata/frcurrents-1.16.1-android-armhf-A32-16.xml
frcurrents_pi Android v1.16.1 
Android Only
> frcurrents_pi Android v1.16.1

- metadata/weather_routing_pi-1.15.21.26-android-arm64-16-android-arm64.xml
- metadata/weather_routing_pi-1.15.21.26-android-armhf-16-android-armhf.xml
- metadata/weather_routing_pi-1.15.21.26-darwin-wx32-arm64-x86_64-14.1-macos.xml
- metadata/weather_routing_pi-1.15.21.26-debian-arm64-11-bullseye-arm64.xml
- metadata/weather_routing_pi-1.15.21.26-debian-arm64-12-bookworm-arm64.xml
- metadata/weather_routing_pi-1.15.21.26-debian-armhf-11-bullseye-armhf.xml
- metadata/weather_routing_pi-1.15.21.26-debian-armhf-12-bookworm-armhf.xml
- metadata/weather_routing_pi-1.15.21.26-debian-x86_64-11-bullseye.xml
- metadata/weather_routing_pi-1.15.21.26-debian-x86_64-12-bookworm.xml
- metadata/weather_routing_pi-1.15.21.26-flatpak-aarch64-22.08-flatpak.xml
- metadata/weather_routing_pi-1.15.21.26-flatpak-aarch64-24.08-flatpak.xml
- metadata/weather_routing_pi-1.15.21.26-flatpak-x86_64-22.08-flatpak.xml
- metadata/weather_routing_pi-1.15.21.26-flatpak-x86_64-24.08-flatpak.xml
- metadata/weather_routing_pi-1.15.21.26-msvc-x86-10.0.20348-MSVC.xml
- metadata/weather_routing_pi-1.15.21.26-msvc-x86-wx32-10.0.20348-MSVC.xml
- metadata/weather_routing_pi-1.15.21.26-ubuntu-x86_64-22.04-jammy.xml
Sebastiens work fixing bugs and improving the plugin.
Removed the older version
> weather_routing 1.15.21.26

- metadata/MeteoVache-1.4.0-darwin-wx32-universal-10.xml
- metadata/MeteoVache-1.4.0-debian-arm64-A64-11.xml
- metadata/MeteoVache-1.4.0-debian-arm64-A64-12.xml
- metadata/MeteoVache-1.4.0-debian-armhf-A32-11.xml
- metadata/MeteoVache-1.4.0-debian-armhf-A32-12.xml
- metadata/MeteoVache-1.4.0-debian-wx32-arm64-A64-11.xml
- metadata/MeteoVache-1.4.0-debian-wx32-armhf-A32-11.xml
- metadata/MeteoVache-1.4.0-debian-wx32-x86_64-11.xml
- metadata/MeteoVache-1.4.0-debian-x86_64-11.xml
- metadata/MeteoVache-1.4.0-debian-x86_64-12.xml
- metadata/MeteoVache-1.4.0-flatpak-aarch64-A64-22.08.xml
- metadata/MeteoVache-1.4.0-flatpak-aarch64-A64-24.08.xml
- metadata/MeteoVache-1.4.0-flatpak-x86_64-22.08.xml
- metadata/MeteoVache-1.4.0-flatpak-x86_64-24.08.xml
- metadata/MeteoVache-1.4.0-msvc-wx32-10.xml
> Update MeteoVache to 1.4.0

- metadata/frcurrents-v1.16.4-android-arm64-A64-16.xml
- metadata/frcurrents-v1.16.4-android-armhf-A32-16.xml
Simplify font to test text for Android. Leaving 1.16.3 in place.
> v1.16.4 android

- metadata/ShipDriver-v3.4.4-android-arm64-A64-16.xml
- metadata/ShipDriver-v3.4.4-android-armhf-A32-16.xml
- metadata/ShipDriver-v3.4.4-darwin-wx32-universal-10.xml
- metadata/ShipDriver-v3.4.4-debian-arm64-A64-11.xml
- metadata/ShipDriver-v3.4.4-debian-arm64-A64-12.xml
- metadata/ShipDriver-v3.4.4-debian-armhf-A32-11.xml
- metadata/ShipDriver-v3.4.4-debian-armhf-A32-12.xml
- metadata/ShipDriver-v3.4.4-debian-wx32-arm64-A64-11.xml
- metadata/ShipDriver-v3.4.4-debian-wx32-armhf-A32-11.xml
- metadata/ShipDriver-v3.4.4-debian-wx32-x86_64-11.xml
- metadata/ShipDriver-v3.4.4-debian-x86_64-11.xml
- metadata/ShipDriver-v3.4.4-debian-x86_64-12.xml
- metadata/ShipDriver-v3.4.4-flatpak-aarch64-A64-22.08.xml
- metadata/ShipDriver-v3.4.4-flatpak-aarch64-A64-24.08.xml
- metadata/ShipDriver-v3.4.4-flatpak-x86_64-22.08.xml
- metadata/ShipDriver-v3.4.4-flatpak-x86_64-24.08.xml
- metadata/ShipDriver-v3.4.4-msvc-wx32-10.xml
Removed v3.4.1, added v3.4.4. Corrects VTG sentence bug.
> ShipDriver-v3.4.4

- metadata/ShipDriver-v3.4.5-android-arm64-A64-16.xml
- metadata/ShipDriver-v3.4.5-android-armhf-A32-16.xml
- metadata/ShipDriver-v3.4.5-darwin-wx32-universal-10.xml
- metadata/ShipDriver-v3.4.5-debian-arm64-A64-11.xml
- metadata/ShipDriver-v3.4.5-debian-arm64-A64-12.xml
- metadata/ShipDriver-v3.4.5-debian-armhf-A32-11.xml
- metadata/ShipDriver-v3.4.5-debian-armhf-A32-12.xml
- metadata/ShipDriver-v3.4.5-debian-wx32-arm64-A64-11.xml
- metadata/ShipDriver-v3.4.5-debian-wx32-armhf-A32-11.xml
- metadata/ShipDriver-v3.4.5-debian-wx32-x86_64-11.xml
- metadata/ShipDriver-v3.4.5-debian-x86_64-11.xml
- metadata/ShipDriver-v3.4.5-debian-x86_64-12.xml
- metadata/ShipDriver-v3.4.5-flatpak-aarch64-A64-22.08.xml
- metadata/ShipDriver-v3.4.5-flatpak-aarch64-A64-24.08.xml
- metadata/ShipDriver-v3.4.5-flatpak-x86_64-22.08.xml
- metadata/ShipDriver-v3.4.5-flatpak-x86_64-24.08.xml
- metadata/ShipDriver-v3.4.5-msvc-wx32-10.xml
Kupofty fixed some more NMEA bugs.
> ShipDriver v3.4.5

- download_xml.sh
- download_xml_bash.sh
Move processing to download_xml.sh and make download_xml_bash.sh call this script with information about this change
> Update to get 50 entries in list.
