- DEVELOPER-INFO.md
- Makefile
- README.md
- make_catalogue.bat
- metadata/squiddio-plugin-1.0.18.2-ubuntu-16.04.xml
- ocpn-plugins.xml
- ocpn-plugins.xsd
- tools/ocpn-metadata
- tools/ocpn-metadata.bat
As heading says:
- python 3.8.0 introduces a filepath object which leads to a crash in ocpn-metadata
- Windows: remove bat files, use standard tools (notably make) instaed.
- Docs refresh: simplified windows usage, remove duplicates from wiki
> Python 3.8.0 fix, documentation update, fix broken windows files

- DEVELOPER-INFO.md
- Makefile
- README.md
- make_catalogue.bat
- metadata/squiddio-plugin-1.0.18.2-ubuntu-16.04.xml
- ocpn-plugins.xml
- ocpn-plugins.xsd
- tools/ocpn-metadata
- tools/ocpn-metadata.bat
A general update,  obsoletes #9 
- Remove windows bat files, use the Makefile instead (make is available in chocolatey).
- python 3.8.0 fix.
- First shot on a xsd schema + validation. *make validate*  checks current ocnp-plugins.xml
- Add an updated build for squiddio/xenial. Closes: OpenCPN/opencpn#1538
> Pr2: General update

- metadata/meta-url-alpha-seandepagnier-rgleason.xml
- ocpn-plugins.xml
Revised PR for meta-url to Sean's Alpha Plugins
The meta-url looks ok, but it looks like ocpn-plugins.xml has been reordered so there appears to be a lot of change, which I think is just switching the order.  This is a bit counter intuitiive for checking on PR's. Don't know if there is a way around that. 
PS: maybe you just want me to cut and paste the new meta-url into ocpn-plugins.xml so the order does not change?
> meta-url-alpha-seandepagnier-rgleason

- metadata/testplugin-plugin-darwin-10.13.6.xml
- metadata/testplugin-plugin-debian-10.xml
- metadata/testplugin-plugin-fedora-29.xml
- metadata/testplugin-plugin-flatpak-18.08.xml
- metadata/testplugin-plugin-mingw-10.xml
- metadata/testplugin-plugin-msvc-10.0.14393.xml
- metadata/testplugin-plugin-ubuntu-16.04.xml
- metadata/testplugin-plugin-ubuntu-18.04.xml
Add 8 versions of testplugin_pi build. Still missing Raspberry PI builds but others are there.
This is the plugin being used to help build the 'generic' build cmake files for building any plugin for the new process.
> Add testplugin to beta stream

- Makefile
- tools/check-metadata-urls
Add a new script which checks that the urls in a metadata file
are available. A new make target 'check-urls' applies this on
ocpn-plugins.xml.
Unfortunately, the checks takes some time.
This is against the master branch. It could be useful to cherry-pick it also into at least beta, so that things could be checked before merged.
> tools: Add url check script (#27).

- tools/ocpn-install.sh
- tools/ocpn-uninstall.sh
Add tool which can install a local tarball in the same way as the
installer. Typically a developer test tool -- a generated
tarball can be tested without the upload/download cycle.
Closes: OpenCPN/OpenCPN#1600
EDIT: fix bug reference
> tools: Add a new ocpn-install tool.

- tools/ocpn-metadata
After 5d5c5f4 the output from ocpn-metadata is way to noisy for regular usage already now, and after adding some more plugins it will generate several pages of  what's basically debug info also on normal use.
Add a --verbose option, and conditionalize the output on this option.
Also, add some info when a ParseError is generated due to for example not well-formed xml input.
Closes: #59
> ocpn-metadata: Decrease noise on nomal usage, enhanced parser error info.

- tools/ocpn-install.sh
- tools/ocpn-uninstall.sh
Trying to handle #60 and also some other interesting features of the oernc plugin:
- Parse the plugin name (common name) from the xml metadata instead of parsing tarball name (#60).
- Accept tarballs with a /usr or /usr/local prefix.
- Accept plugin (common) names  containing spaces.  This makes it work for now, but creates manifest and version files with spaces in filename. 
- Add raspbian to the list of supported target os'es. 
- While on it, enhance the runtime usage info in scripts.
Closes: #60
> Common name

- ocpn-plugins.xsd
Fix a typo in 5285f93 which makes the xsd file useless due to syntax errors (sorry!).
> ocpn-plugins.xsd: Fix typo making "make validate" fail.

- ocpn-plugin.xsd
- ocpn-plugins.xsd
Fixes for #112 (constrain target and target-arch  values) and #115 (support validation of single XML metadata file).
These patches contains lists of allowed values for target and target-arch. These need to be reviewed, I don't have the complete picture.
The PR supports validating a single  plugin metadata file using something like 
xmllint  --schema ocpn-plugin.xsd  --noout \
metadata/windvane_pi-1.0.13.0_ubuntu-amd64_20.04-focal.xml
Running `make validate`on current ocpn-plugins.xml  using this PR gives about 120 errors; log is attached. Possibly, some of these errors should be fixed by modifying the xsd, but the bulk is certainly errors in the xml file.
[validate.log](https://github.com/OpenCPN/plugins/files/4748613/validate.log)
> Xsd update -- constrain values and handle plugin metadata (#112, #115)

- metadata/vfkaps_pi-2.1.1.7-darwin-x86_64-10.13.6-macos.xml
- metadata/vfkaps_pi-2.1.1.7-debian-x86_64-10-buster.xml
- metadata/vfkaps_pi-2.1.1.7-flatpak-x86_64-18.08-flatpak.xml
- metadata/vfkaps_pi-2.1.1.7-mingw-x86_64-10-mingw.xml
- metadata/vfkaps_pi-2.1.1.7-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/vfkaps_pi-2.1.1.7-raspbian-armhf-10-buster-armhf.xml
- metadata/vfkaps_pi-2.1.1.7-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/vfkaps_pi-2.1.1.7-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/vfkaps_pi-2.1.1.7-ubuntu-x86_64-14.04-trusty.xml
- metadata/vfkaps_pi-2.1.1.7-ubuntu-x86_64-16.04-xenial.xml
- metadata/vfkaps_pi-2.1.1.7-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/vfkaps_pi-2.1.1.7-ubuntu-x86_64-18.04-bionic.xml
- metadata/vfkaps_pi-2.1.1.7-ubuntu-x86_64-20.04-focal-gtk3.xml
Updated vfkaps_pi. Upper/lower case was causing issues with the managed plugin installing over a previously installed version. The case in the managed plugins list did not match the name of the installed plugin in the installed list (I think!).
Thanks again Dave.
> vfkaps-2.1.1.7

- README.md
- metadata/race_start_display_pi-1.1.0.0-darwin-x86_64-10.13.6-macos.xml
- metadata/race_start_display_pi-1.1.0.0-debian-x86_64-10-buster.xml
- metadata/race_start_display_pi-1.1.0.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/race_start_display_pi-1.1.0.0-mingw-x86_64-10-mingw.xml
- metadata/race_start_display_pi-1.1.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/race_start_display_pi-1.1.0.0-raspbian-armhf-10-buster-armhf.xml
- metadata/race_start_display_pi-1.1.0.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/race_start_display_pi-1.1.0.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/race_start_display_pi-1.1.0.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/race_start_display_pi-1.1.0.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/race_start_display_pi-1.1.0.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/race_start_display_pi-1.1.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/race_start_display_pi-1.1.0.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Race Start Display plugin ported to new Plugin Manager model. Builds successfully compiled by Continuous Integration systems (CircleCI, Travis &  Appveyor) and resulting metadata, packages and tarballs uploaded to Cloudsmith. Metadata files successfully checked with xmllint, validate_xml.sh and check-metadata-urls scripts.
> Race Start Display

- metadata/dashboardtactics_pi-1.6.6.0-darwin-x86_64-10.13.6-macos.xml
- metadata/dashboardtactics_pi-1.6.6.0-debian-x86_64-10-buster.xml
- metadata/dashboardtactics_pi-1.6.6.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/dashboardtactics_pi-1.6.6.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/dashboardtactics_pi-1.6.6.0-raspbian-armhf-10-buster-armhf.xml
- metadata/dashboardtactics_pi-1.6.6.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/dashboardtactics_pi-1.6.6.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/dashboardtactics_pi-1.6.6.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/dashboardtactics_pi-1.6.6.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/dashboardtactics_pi-1.6.6.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Missing Mingw and Trusty because they use earlier version of wxWidgets and are making errors.
If someone can give the the wx include to fix this I will rebuild and push those builds up too.
> dashboardtactics 1.6.6.0 + fe2 v1.0.132

- metadata/twocan_plugin_pi-1.9.0.0-darwin-x86_64-10.13.6-macos.xml
- metadata/twocan_plugin_pi-1.9.0.0-debian-x86_64-10-buster.xml
- metadata/twocan_plugin_pi-1.9.0.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/twocan_plugin_pi-1.9.0.0-mingw-x86_64-10-mingw.xml
- metadata/twocan_plugin_pi-1.9.0.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/twocan_plugin_pi-1.9.0.0-raspbian-armhf-10-buster-armhf.xml
- metadata/twocan_plugin_pi-1.9.0.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/twocan_plugin_pi-1.9.0.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/twocan_plugin_pi-1.9.0.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/twocan_plugin_pi-1.9.0.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/twocan_plugin_pi-1.9.0.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/twocan_plugin_pi-1.9.0.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/twocan_plugin_pi-1.9.0.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Updated version of TwoCan plugin to support OpenCPN 5.2 & Plugin Manager.
Passed XSD and URL verification checks
> TwoCan plugin v1.9

- Makefile
- README.md
- TESTING.md
- ocpn-plugin.xsd
- pre-commit
- tools/check-metadata-urls
- tools/ocpn-metadata
EDIT: Updated the PR which now 
- Removes illegal archs  and targets (https://github.com/OpenCPN/OpenCPN/issues/2003)
- Fixes for check-metadata-urls to accept a single metadata file.
- Fixes for pre-commit to also check urls.
- Add a check-urls Makefile convenience target.
- Documentation updates, partly after discussions in https://github.com/OpenCPN/OpenCPN/issues/2031. This PR should close that discussion.
EDIT2: 
- Improves parsing  error messages from ocpn-metadata
EDIT3:
- Fix for xsd schema so it can be used to validate a single plugin metadata file.
EDIT4:
- Add xsd support for data-only plugins for all targets.
- Let ocpn-metadata keep going on parse errors.
> Fixes for checking single metadata files, docs (OpenCPN#2031)

- ocpn-plugin.xsd
The correct value for the mingw target value is 'mingw-x86_64', but most
plugins are using the bad value 'mingw'. Allwo both values during a
transition window.
See: https://github.com/OpenCPN/OpenCPN/issues/2061.
> Fix bad mingw target value (OpenCPN#2061).

- metadata/twocan_plugin_pi-1.9.1.0-darwin-x86_64-10.13.6-macos.xml
- metadata/twocan_plugin_pi-1.9.1.0-debian-x86_64-10-buster.xml
- metadata/twocan_plugin_pi-1.9.1.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/twocan_plugin_pi-1.9.1.0-mingw-x86_64-10-mingw.xml
- metadata/twocan_plugin_pi-1.9.1.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/twocan_plugin_pi-1.9.1.0-raspbian-armhf-10-buster-armhf.xml
- metadata/twocan_plugin_pi-1.9.1.0-raspbian-armhf-9.4-stretch-armhf.xml
- metadata/twocan_plugin_pi-1.9.1.0-ubuntu-arm64-18.04-bionic-armh64.xml
- metadata/twocan_plugin_pi-1.9.1.0-ubuntu-x86_64-14.04-trusty.xml
- metadata/twocan_plugin_pi-1.9.1.0-ubuntu-x86_64-16.04-xenial.xml
- metadata/twocan_plugin_pi-1.9.1.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/twocan_plugin_pi-1.9.1.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/twocan_plugin_pi-1.9.1.0-ubuntu-x86_64-20.04-focal-gtk3.xml
Minor update to TwoCan plugin.
1. Add support for PGN 129540 GNSS Satellites in View
2. Fix random GPS position fix (missing break statement)
3. Reliability improvement, when shutting down on an idle NMEA 2000 network,
XML metadata files pass XSD & URL validation checks
> TwoCan plugin v1.9.1

- metadata/TideFinder-1.4-darwin-10.13.6.xml
- metadata/TideFinder-1.4-debian-10.xml
- metadata/TideFinder-1.4-flatpak-18.08.xml
- metadata/TideFinder-1.4-mingw-10.xml
- metadata/TideFinder-1.4-msvc-10.0.14393.xml
- metadata/TideFinder-1.4-raspbian-10.xml
- metadata/TideFinder-1.4-raspbian-9.13.xml
- metadata/TideFinder-1.4-ubuntu-16.04.xml
- metadata/TideFinder-1.4-ubuntu-18.04.xml
- metadata/TideFinder-1.4-ubuntu-gtk3-18.04.xml
- metadata/TideFinder-1.4-ubuntu-gtk3-20.04.xml
- ocpn-plugins.xml
v1.4.3
Sorry... this is to correct a typo. Tide Finder now replaced by TideFinder for the common name. Without this the plugin list had problems.
Dave... Is the Beta Catalog being removed from OpenCPN? Not seen in a recent compilation of the master code.
> Update TideFinder to correct Typo

- cloudsmith-sync.sh
- metadata/radar_pi-5.2.0-beta4-ov51-darwin-10.15.1.xml
- metadata/radar_pi-5.2.0-beta4-ov51-debian-x86_64-10.xml
- metadata/radar_pi-5.2.0-beta4-ov51-mingw-10.xml
- metadata/radar_pi-5.2.0-beta4-ov51-msvc-10.0.14393.xml
- metadata/radar_pi-5.2.0-beta4-ov51-raspbian-armhf-10.xml
- metadata/radar_pi-5.2.0-beta4-ov51-raspbian-armhf-9.4.xml
- metadata/radar_pi-5.2.0-beta4-ov51-ubuntu-gtk3-x86_64-20.04.xml
- metadata/radar_pi-5.2.0-beta4-ov51-ubuntu-x86_64-16.04.xml
- metadata/radar_pi-5.2.0-beta4-ov51-ubuntu-x86_64-18.04.xml
Another beta for the plugin. This fixes version number detection on newer HALOs and enables Doppler in a non-chartplotter scenario.
> radar_pi 5.2.0-beta4

- ocpn-plugin.xsd
First part of https://github.com/OpenCPN/OpenCPN/issues/2185, to define proper ABI naming scheme for Arm platforms.
> ocpn-plugin.xsd: New arm platforms.

- ocpn-plugin.xsd
Since arm64 Flatpak uses aarch64 rather than Debian's arm64 we need to
add aarch64 to the allowed arches.
Document  that build-host and build-gtk have been obsoleted. Since
the checksum is implemented, remove comment about the opposite.
> ocpn-plugin.xsd: Add aarch64 target, update comments.

- metadata/ShipDriver-2.7-android-arm64-A64-16.xml
- metadata/ShipDriver-2.7-android-armhf-16.xml
- metadata/ShipDriver-2.7-darwin-10.13.6.xml
- metadata/ShipDriver-2.7-debian-10.xml
- metadata/ShipDriver-2.7-flatpak-18.08.xml
- metadata/ShipDriver-2.7-flatpak-20.08.xml
- metadata/ShipDriver-2.7-flatpak-A64-20.08.xml
- metadata/ShipDriver-2.7-msvc-10.0.14393.xml
- metadata/ShipDriver-2.7-raspbian-10.xml
- metadata/ShipDriver-2.7-raspbian-9.13.xml
- metadata/ShipDriver-2.7-ubuntu-16.04.xml
- metadata/ShipDriver-2.7-ubuntu-18.04.xml
- metadata/ShipDriver-2.7-ubuntu-gtk3-18.04.xml
- metadata/ShipDriver-2.7-ubuntu-gtk3-20.04.xml
Raspbian still not building a prod version with Drone.io, only making an alpha in Cloudsmith. tbc.
> Update for ShipDriver following attempts to rectify Raspbian problems

- metadata/meta-url-alpha-rg-plugins.xml
- ocpn-plugins.xml
> Alpha - update rg & jg meta-urls to be for Alpha branch and new xsd format

- .circleci/config.yml
- tools/ci-check
Add a circleci job which checks all updated urls (as compared with upstream).
Obviously, this means that circleci must be configured to build this project, but that should be enough to have all PR:s checked.
This approach actually allows checking also checksums (which means downloading all plugins and comparing). it's a bit slow, but it should be acceptable in this context.
> ci: Add an automated ci url check.

- .github/workflows/cronjob.yml
Add a nightly job which checks for broken metadata urls. This should
pick up cases where urls was ok when merged into the catalog, but later
broken when tarballs disappear from cloudsmith (which seems to happen).
An example on output is available at
https://github.com/leamas/plugins/runs/3283583545?check_suite_focus=true
This is the last part of planned PRs to handle #383
> Add a nightly metadata check (#383)

- metadata/ShipDriver-v2.8.6.0-android-arm64-A64-16.xml
- metadata/ShipDriver-v2.8.6.0-android-armhf-16.xml
- metadata/ShipDriver-v2.8.6.0-darwin-10.13.6.xml
- metadata/ShipDriver-v2.8.6.0-debian-10.xml
- metadata/ShipDriver-v2.8.6.0-flatpak-18.08.xml
- metadata/ShipDriver-v2.8.6.0-flatpak-20.08.xml
- metadata/ShipDriver-v2.8.6.0-flatpak-A64-20.08.xml
- metadata/ShipDriver-v2.8.6.0-msvc-10.0.14393.xml
- metadata/ShipDriver-v2.8.6.0-raspbian-10.xml
- metadata/ShipDriver-v2.8.6.0-raspbian-9.13.xml
- metadata/ShipDriver-v2.8.6.0-ubuntu-16.04.xml
- metadata/ShipDriver-v2.8.6.0-ubuntu-18.04.xml
- metadata/ShipDriver-v2.8.6.0-ubuntu-gtk3-18.04.xml
- metadata/ShipDriver-v2.8.6.0-ubuntu-gtk3-20.04.xml
- ocpn-plugins.xml
This is an attempt to fix broken URLs in the master catalog.
v2.8.5.1 in the beta catalog will shortly be removed.
> Create ShipDriver v2.8.6 in master catalog

- metadata/ais-vd-v1.2.0-darwin-wx315-10.13.6.xml
- metadata/ais-vd-v1.2.0-debian-10.xml
- metadata/ais-vd-v1.2.0-flatpak-18.08.xml
- metadata/ais-vd-v1.2.0-flatpak-20.08.xml
- metadata/ais-vd-v1.2.0-flatpak-A64-20.08.xml
- metadata/ais-vd-v1.2.0-msvc-10.0.14393.xml
- metadata/ais-vd-v1.2.0-raspbian-11.xml
- metadata/ais-vd-v1.2.0-ubuntu-16.04.xml
- metadata/ais-vd-v1.2.0-ubuntu-18.04.xml
- metadata/ais-vd-v1.2.0-ubuntu-gtk3-18.04.xml
- metadata/ais-vd-v1.2.0-ubuntu-gtk3-20.04.xml
A new plugin for ships using a AIS class A transponder to help update what's called "static voyage data". That's destination and if they intend to sail or go by motor etc.  
Not for so many average OCPN users but still handy for the few. To enter these data into a AIS device can be hard. Not less if there are many characters for the destination.
> ais-vd_pi meta

- metadata/engine_dashboard_pi-1.4.1.0-msvc-x86_64-10.0.14393-MSVC.xml
- ocpn-plugins.xml
For some reason appveyor missed the git hub commit and failed to build the msvc release,.
Passes XSD and url checks,
> Missing Engine Dashboard 1.4.1.0 MSVC build

- ocpn-plugin.xsd
Since we don't plan to support ubuntu on arm64/aarch64 the corresponding
target are removed. OTOH, we need ubuntu-armhf targets due to https://github.com/OpenCPN/OpenCPN/discussions/2502.
> ocpn-plugin.xsd: Drop ubuntu-arm64, add ubuntu-armhf targets (OCPN#2502)

- metadata/SailawayNMEA-v0.4-beta2-darwin-wx315-10.13.6.xml
- metadata/SailawayNMEA-v0.4-beta2-msvc-10.0.14393.xml
Move to managed version (ShipDriver). Only for MacOS and Win.
> SailawayNMEA v0.4-beta2

- README.md
- TESTING.md
Add a chapter in TESTING.md on creating a private, published catalog which can be used as custoim URL. The purpose is really that we should be able to drop the meta-url kludge by documenting this loophole.
I don't expect anyone to find this info without help, it's buried in tons of other stuff. However, we could provide some help when need be. 
In order to make this more useful: please update README.md , TESTING.md and the complete tools directory also on Beta and Alpha branch.
> Document custom URL usecase

- metadata/testplugin_pi-1.0.193.1-android-arm64-16-android-arm64.xml
- metadata/testplugin_pi-1.0.193.1-android-armhf-16-android-armhf.xml
- metadata/testplugin_pi-1.0.193.1-darwin-wx315-x86_64-11.4-macos.xml
- metadata/testplugin_pi-1.0.193.1-darwin-x86_64-11.4-macos.xml
- metadata/testplugin_pi-1.0.193.1-debian-armhf-10.xml
- metadata/testplugin_pi-1.0.193.1-debian-armhf-11.xml
- metadata/testplugin_pi-1.0.193.1-debian-x86_64-10-buster.xml
- metadata/testplugin_pi-1.0.193.1-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/testplugin_pi-1.0.193.1-flatpak-x86_64-18.08-flatpak.xml
- metadata/testplugin_pi-1.0.193.1-flatpak-x86_64-20.08-flatpak.xml
- metadata/testplugin_pi-1.0.193.1-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/testplugin_pi-1.0.193.1-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/testplugin_pi-1.0.193.1-raspbian-armhf-9.13.xml
- metadata/testplugin_pi-1.0.193.1-ubuntu-armhf-18.04.xml
- metadata/testplugin_pi-1.0.193.1-ubuntu-armhf-20.04.xml
- metadata/testplugin_pi-1.0.193.1-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/testplugin_pi-1.0.193.1-ubuntu-x86_64-18.04-bionic.xml
- metadata/testplugin_pi-1.0.193.1-ubuntu-x86_64-20.04-focal-gtk3.xml
Add -gtk3 to target for ubuntu versions 18.04 & 20.04 that are built with gtk3
> update for -gtk3 added to all ubuntu builds for gtk3

- metadata/climatology_pi-1.4.41.0-darwin-wx315-x86_64-11.4-macos.xml
- metadata/climatology_pi-1.4.41.0-darwin-x86_64-11.4-macos.xml
- metadata/climatology_pi-1.4.41.0-debian-armhf-10.xml
- metadata/climatology_pi-1.4.41.0-debian-armhf-11.xml
- metadata/climatology_pi-1.4.41.0-debian-x86_64-10-buster.xml
- metadata/climatology_pi-1.4.41.0-flatpak-aarch64-20.08-flatpak-arm64.xml
- metadata/climatology_pi-1.4.41.0-flatpak-x86_64-18.08-flatpak.xml
- metadata/climatology_pi-1.4.41.0-flatpak-x86_64-20.08-flatpak.xml
- metadata/climatology_pi-1.4.41.0-flatpak-x86_64-wx315-20.08-flatpak.xml
- metadata/climatology_pi-1.4.41.0-msvc-x86_64-10.0.14393-MSVC.xml
- metadata/climatology_pi-1.4.41.0-raspbian-armhf-9.13.xml
- metadata/climatology_pi-1.4.41.0-ubuntu-armhf-18.04.xml
- metadata/climatology_pi-1.4.41.0-ubuntu-armhf-20.04.xml
- metadata/climatology_pi-1.4.41.0-ubuntu-x86_64-18.04-bionic-gtk3.xml
- metadata/climatology_pi-1.4.41.0-ubuntu-x86_64-18.04-bionic.xml
- metadata/climatology_pi-1.4.41.0-ubuntu-x86_64-20.04-focal-gtk3.xml
For some reason many (most) of the v1.4.40 are no longer found on Cloudsmith. I have been unable to explain this. I have not found a "history" on Cloudsmith so that avenue is not available. This version is to replace that 1.4.40
> climatology 1.4.41

- ocpn-plugin.xsd
As heading says. This is just preparations for the 5.8.0 cycle, to define things and at least let them pass basic xsd validation.
> Add new targets for native macOS arm  and windows 64-bit builds

- ocpn-plugin.xsd
In Debian 10 there are both gtk3-based official builds and gtk2
based PPA builds. We need to formalize this fact using a separate
ABI for Debian 10, similar to ubuntu-gtk3. This applies whether
we we actually build plugins for debian-gtk3-armhf or not.
See: https://github.com/OpenCPN/OpenCPN/issues/2612
> xsd: Add new debian-gtk3-armhf ABI spec

- ocpn-plugin.xsd
Add a new ABI for windows plugins using  wxwidgets 3.2.x
> ocpn-plugin.xsd: New ABI designator msvc-wx32

- ocpn-plugin.xsd
Retire obsolete wx315 transitional ABIs.
Add -wx32 ABI for all debian builds, which will be needed for Ubuntu 22.04 which will use both wx3.0 and and wx 3.2.
Flatpak and MacOS will only use either wx3.0 or wx3.2 for all versions, so no -wx32 is required for these. msvc-wx32 is already in place.
See: https://github.com/OpenCPN/OpenCPN/discussions/2502
> Update wx32-dependent types (opencpn#2502).

- ocpn-plugin.xsd
For both technical reasons and just to be consistent types like _debian-armhf_wx32_ should be _debian_wx32_armhf_ etc.
> Correct new, buggy ABI types in #747 (OpenCPN#2797).

- ocpn-plugin.xsd
As discussed in https://github.com/OpenCPN/OpenCPN/discussions/2797: add  a new ABI specification for wx32-based plugins on MacOS.
> ocpn-plugin: Add new abi darwin-wx32 (OpenCPN#2797)

- metadata/Radar-v5.5.0-beta-darwin-wx32-10.xml
- metadata/Radar-v5.5.0-beta-debian-11.xml
- metadata/Radar-v5.5.0-beta-debian-A32-11.xml
- metadata/Radar-v5.5.0-beta-debian-A64-11.xml
- metadata/Radar-v5.5.0-beta-debian-wx32-A64-11.xml
- metadata/Radar-v5.5.0-beta-flatpak-A64-22.08.xml
- metadata/Radar-v5.5.0-beta-msvc-wx32-10.xml
Due to a botched patchup the download process did not re-download the files created in an earlier attempt and so the wrong checksums were committed.
> Fix checksums for radar v5.5.0-beta

- tools/check-metadata-urls
Add some handling for empty urls. This reports grib as problematic since it's url is empty. It should be pretty clear that that this is not an  actual issue, though.
Closes: #929
> check-metadata-urls: Handle empty urls

- metadata/chartdownloader-all.xml
- metadata/dashboard-all.xml
- metadata/grib-all.xml
- metadata/wmm-all.xml
- ocpn-plugin.xsd
- tools/check-metadata-urls
This is basically support for https://github.com/OpenCPN/OpenCPN/pull/3258 which notably adds the website button also to the system plugins. Overall, it also seems more consistent to have the metadata in  the catalog also for the system plugins.
While on it, fix two bugs: one in the xsd file and one on check-metadata-urls.
EDIT: The check-metadata-urls fix is basically a hack. We need to update basically all files besides the metadata  from master to Beta.
> System  plugin metadata

- ocpn-plugin.xsd
Per discussions in https://github.com/OpenCPN/OpenCPN/issues/2027 we need windows arch specifier which reflects the actual win32 plugins we build. Added _x86_.
> New <target-arch> i386

- metadata/Radar-v5.5.4-beta-darwin-wx32-universal-10.xml
- metadata/Radar-v5.5.4-beta-debian-11.xml
- metadata/Radar-v5.5.4-beta-debian-12.xml
- metadata/Radar-v5.5.4-beta-debian-A32-11.xml
- metadata/Radar-v5.5.4-beta-debian-A32-12.xml
- metadata/Radar-v5.5.4-beta-debian-A64-11.xml
- metadata/Radar-v5.5.4-beta-debian-A64-12.xml
- metadata/Radar-v5.5.4-beta-debian-wx32-11.xml
- metadata/Radar-v5.5.4-beta-debian-wx32-A32-11.xml
- metadata/Radar-v5.5.4-beta-debian-wx32-A64-11.xml
- metadata/Radar-v5.5.4-beta-flatpak-22.08.xml
- metadata/Radar-v5.5.4-beta-flatpak-A64-22.08.xml
- metadata/Radar-v5.5.4-beta-msvc-wx32-10.0.20348.xml
Testing found some build/git issues in 5.5.3, so we're up to 5.5.4.
> Radar v5.5.4-beta

- metadata/gpsodometer_pi-0.8.11.0-android-arm64-16-android-arm64.xml
- metadata/gpsodometer_pi-0.8.11.0-android-armhf-16-android-armhf.xml
- metadata/gpsodometer_pi-0.8.11.0-darwin-wx32-arm64-x86_64-14.1-macos.xml
- metadata/gpsodometer_pi-0.8.11.0-debian-arm64-11-bullseye-arm64.xml
- metadata/gpsodometer_pi-0.8.11.0-debian-arm64-12-bookworm-arm64.xml
- metadata/gpsodometer_pi-0.8.11.0-debian-armhf-11-bullseye-armhf.xml
- metadata/gpsodometer_pi-0.8.11.0-debian-armhf-12-bookworm-armhf.xml
- metadata/gpsodometer_pi-0.8.11.0-debian-x86_64-11-bullseye.xml
- metadata/gpsodometer_pi-0.8.11.0-debian-x86_64-12-bookworm.xml
- metadata/gpsodometer_pi-0.8.11.0-flatpak-aarch64-22.08-flatpak.xml
- metadata/gpsodometer_pi-0.8.11.0-flatpak-aarch64-24.08-flatpak.xml
- metadata/gpsodometer_pi-0.8.11.0-flatpak-x86_64-22.08-flatpak.xml
- metadata/gpsodometer_pi-0.8.11.0-flatpak-x86_64-24.08-flatpak.xml
- metadata/gpsodometer_pi-0.8.11.0-msvc-x86-10.0.20348-MSVC.xml
- metadata/gpsodometer_pi-0.8.11.0-msvc-x86-wx32-10.0.20348-MSVC.xml
- metadata/gpsodometer_pi-0.8.11.0-ubuntu-x86_64-22.04-jammy.xml
Dave,
0.8.11   has 16 metadata files  - I hope they all work now.
0.8.10  had 14 metadata files - they are being removed.
I believe the problem for the  GPSodometer  3 PRs  was Cloudsmith was unable to accept the tarball for some glitch y reason and thus called it a "duplicate" and flagged it with a little red ball at the top left. There was a message to delete the second copy, which I did. However there then was no first copy either!  So the answer is to increment the version, build it and push again to catalog.
Hope this works.
> gpsodometer 0.8.11 + rm 0.8.10

- metadata/VDR-v1.3.65.0-android-arm64-A64-16.xml
- metadata/VDR-v1.3.65.0-android-armhf-A32-16.xml
- metadata/VDR-v1.3.65.0-darwin-wx32-universal-10.xml
- metadata/VDR-v1.3.65.0-debian-arm64-A64-11.xml
- metadata/VDR-v1.3.65.0-debian-arm64-A64-12.xml
- metadata/VDR-v1.3.65.0-debian-armhf-A32-11.xml
- metadata/VDR-v1.3.65.0-debian-armhf-A32-12.xml
- metadata/VDR-v1.3.65.0-debian-wx32-arm64-A64-11.xml
- metadata/VDR-v1.3.65.0-debian-wx32-armhf-A32-11.xml
- metadata/VDR-v1.3.65.0-debian-wx32-x86_64-11.xml
- metadata/VDR-v1.3.65.0-debian-x86_64-11.xml
- metadata/VDR-v1.3.65.0-debian-x86_64-12.xml
- metadata/VDR-v1.3.65.0-flatpak-aarch64-A64-22.08.xml
- metadata/VDR-v1.3.65.0-flatpak-aarch64-A64-24.08.xml
- metadata/VDR-v1.3.65.0-flatpak-x86_64-22.08.xml
- metadata/VDR-v1.3.65.0-flatpak-x86_64-24.08.xml
- metadata/VDR-v1.3.65.0-msvc-wx32-10.xml
bdbcat Fixed by [Adjust SVG icon sizes for scaled display on Windows](https://github.com/rgleason/vdr_pi/commit/c895a03b979f4862973b5cafbdf6b22f415f3f44)  Badly Sized Icons.
> vdr 1.3.65 and remove previous 

- metadata/ShipDriver-v3.4.6-android-arm64-A64-16.xml
- metadata/ShipDriver-v3.4.6-android-armhf-A32-16.xml
- metadata/ShipDriver-v3.4.6-darwin-wx32-universal-10.xml
- metadata/ShipDriver-v3.4.6-debian-arm64-A64-11.xml
- metadata/ShipDriver-v3.4.6-debian-arm64-A64-12.xml
- metadata/ShipDriver-v3.4.6-debian-armhf-A32-11.xml
- metadata/ShipDriver-v3.4.6-debian-armhf-A32-12.xml
- metadata/ShipDriver-v3.4.6-debian-wx32-arm64-A64-11.xml
- metadata/ShipDriver-v3.4.6-debian-wx32-armhf-A32-11.xml
- metadata/ShipDriver-v3.4.6-debian-wx32-x86_64-11.xml
- metadata/ShipDriver-v3.4.6-debian-x86_64-11.xml
- metadata/ShipDriver-v3.4.6-debian-x86_64-12.xml
- metadata/ShipDriver-v3.4.6-flatpak-aarch64-A64-22.08.xml
- metadata/ShipDriver-v3.4.6-flatpak-aarch64-A64-24.08.xml
- metadata/ShipDriver-v3.4.6-flatpak-x86_64-22.08.xml
- metadata/ShipDriver-v3.4.6-flatpak-x86_64-24.08.xml
- metadata/ShipDriver-v3.4.6-msvc-wx32-10.xml
Remove v3.4.5. 
v3.4.6 corrects a bug in the RMC Sentence generated by ShipDriver.
Thanks to the Data Monitor tool for detecting this.
> ShipDriver v3.4.6

- download_xml.sh
- download_xml_bash.sh
Move processing to download_xml.sh and make download_xml_bash.sh call this script with information about this change
> Update to get 50 entries in list.
